- src/api.tf
- src/api_product/app_io/policy.xml.tmpl
- src/variables.tf
Reference AppIo Timeout from terraform variable instead of an APIM Named Value
---
> Set appio timeout sec from terraform and not apim named values

- src/aks.tf
- src/variables.tf
Allow to change vm size and node count between envs of the default node pool.
When changing vm size of the default node pool you need to manually do:
```bash
az aks nodepool add \
--cluster-name cstar-d-aks \
--resource-group cstar-d-aks-rg \
--name temp \
--mode "System"
```
Warning: This will cause running applications and workloads on the "Default Node Pool" to stop and migrate over to another node before they get restarted.
```bash
az aks nodepool delete \
--cluster-name  cstar-d-aks \
--resource-group cstar-d-aks-rg \
--name default
```
Re create the default pool with correct vm size:
```bash
az aks nodepool add \
--cluster-name cstar-d-aks \
--resource-group cstar-d-aks-rg \
--name default \
--mode "System" \
--node-vm-size "Standard_DS3_v2" \
--node-osdisk-type "Managed" \ …
```
> Allow to change aks vm size and node count

- src/psql/subscriptions/DEV-CSTAR/terraform.tfvars
```
Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for relation bpd_citizen_notenabled
Where: SQL statement "truncate table bpd_citizen.bpd_citizen_notEnabled"
PL/pgSQL function update_bonifica_recesso_citizen(character varying) line 53 at SQL statement
```
---
> Add truncate grant to bpd_citizen

- src/api.tf
> Fix service url since ingress http

- src/api_product/app_io/policy.xml.tmpl
As requested by Menotti:
"sulla policy dell’APIM di UAT mettiamo il fallback sull’autenticazione, così non dobbiamo neppure switchare alla bisogna:
se token non trovato nel mock --> chiamo backend di IO"
---
> Authorization header check fallback towards io backend if error

- src/network.tf
Enable routing from vpn gateway to vnet integration
`azurevpnconfig.xml` needs these changes:
`prod`  routing to 10.230.6.0/24 is pushed by vpn gateway, no include routes are needed
```xml
<clientconfig>
<dnsservers>
<dnsserver>10.1.134.4</dnsserver>
</dnsservers>
</clientconfig>
```
`uat` routing to 10.230.7.0/24 is pushed by vpn gateway, no include routes are needed
```xml
<clientconfig>
<dnsservers>
<dnsserver>10.1.133.4</dnsserver>
</dnsservers>
</clientconfig>
```
---
> Fix vpn routing to vnet integration

- src/aks/rbac.tf
update aks rbac
- rename contributors group to developers
- add operations group
- add technical-project-managers group
align aks rbac with azure ad groups https://github.com/pagopa/pagopa-authorization/pull/63
---
> Align rbac to azure ad groups

- src/default.tf
add fake `default-roleassignment-rg`
A service principal or user need to access at least one resource inside a subscription.
`default-roleassignment-rg` it's a fake resource
---
> Add default resource group for role assignment

- src/env/dev/terraform.tfvars
- src/env/prod/terraform.tfvars
- src/env/uat/terraform.tfvars
This PR proposes to fix some configuration variables related to Postgres memory management after the scale down of the prod environment. The same rationale is applied to other envs (dev and uat) to fix the configuration.
- Set `effective_cache_size = 0.5 x Tot RAM` (this reference suggests 0.7 x Tot RAM, but 0.5 is more conservative https://www.cybertec-postgresql.com/en/effective_cache_size-what-it-means-in-postgresql/ )
- Halved `maintenance_work_mem`, as the RAM of the DBMS has been halved (this setting is kept constant in all environment)
- Set `autovacuum_work_mem = -1`, with this setting the autovacuum work memory is managed by the DBMS from 0 to `autovacuum_max_workers x maintenance_work_mem`
While migrating the system, configuration of the DBMS  has been mirrored in our …
> [CEN-666] Fix Postgres Configuration

- src/k8s/bpd_deployments.tf
This PR proposes to use the resource `kubernetes_horizontal_pod_autoscaler` to link number of pods in a deployment to CPU load, which in turn is related to system load. 
- A new Horizontal Pod Autoscaler for citizen deployment
Pod autoscaling is an effective way to reduce cluster costs
---
> [CEN-746] Horizontal Autoscaler for Citizen Deployment

- src/k8s/fa_configmaps.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
- src/k8s/variables.tf
This PR proposes to add a new Configmap in k8s cluster needed to deploy microservice Enrollment
- New configmap for ms enrollment
- Minor fixes to `fatransaction` configmap
- TF variables to customize enrollment configmap in each environment
This changes are required to deploy ms Enrollment
Main branch doesn't reflect true status of the infrastructure due to work on horizontal pod autoscaling in another branch (https://github.com/pagopa/cstar-infrastructure/pull/205)
---
> [CEN-780] Configmap for Enrollment Microservice

- src/k8s/fa_configmaps.tf
- src/k8s/fa_secrets.tf
- src/k8s/secrets.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- Update value of env var to insert ingress ip for invocation of APIs between different namespaces
This change is mandatory in order to invoke APIs exposed by BPD's mock from FA microservice
---
> set ingress ip to invoke bpd's mock api

- src/psql/migrations/PROD-CSTAR/bpd/V9__bpd_backup_citizen_ranking_for_supercashback.sql
This PR proposes to clone the table `bpd_citizen_ranking` as a backup for disaster recovery just in case we experience problems while computing supercashback ranking
- A new backup table with data and structure from `bpd_citizen_ranking`
- Grant select privileges to Operations Departement
This PR is a way to enable disaster recovery just in case computation of supercashback ranking would produce  irreversible errors. 
---
> [CEN-931] Simple clone (no indexes nor columns attributes) of bpd_citizen_ranking

- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
This PR proposes to add an horizontal pod autoscaler for micro-service award period.
- New HPA resource for micro-service award period
Micro-service autoscaling
---
> [CEN-979] HPA for micro-service Award Period

- src/env/prod/terraform.tfvars
In order to reduce costs, this PR proposes to scale down the DBMS
- Set DBMS SKU to `GEN 5 8 core`
- Remove Custom configs of the DBMS (set default values)
Due to disposal of the Cashback program, the load on the system is heavily reduced, so cost and resources should be cut down
The plan proposes 16 resource deletion, but this is normal since I have removed custom configuration (to set the defaults) and each conf variable counts as a resource. 
---
> [CEN-1002] Scale Down PROD DB

- src/env/prod/terraform.tfvars
- src/env/uat/terraform.tfvars
This PR proposes to further reduce PROD DBMS SKU to GEN 5 - 4 core and remove optimization in UAT.
- Update SKU of prod DBMS to GEN 5 4 core
- Remove UAT DBMS custom configs
- Update alarm threshold  
This change is required to cut system costs
---
> [CEN-1012] Scale down DB to 4 core and remove custom configs

- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
This PR enables [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) for the bpdmsawardwinner deployment.
- HPA for deployment bpdmsawardwinner
This change allow us to move away from a fixed allocation of resources in order to optimize operational costs.
---
> [CEN-1006] Add HPA for microservice award winner

- src/aks.tf
- src/env/prod/terraform.tfvars
- src/variables.tf
This PR proposes to enable node (horizontal) autoscaling on production cluster.
- add new variables to enable autoscaling and set min and max nodes
This PR solves the problem of minimizing the cost of the cluster  
---
> [CEN-1032] Cluster autoscaling

- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
This PR enables [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) for the bpdmstransactionerrormanager deployment.
- HPA for deployment bpdmstransactionerrormanager
This change allows us to move away from a fixed allocation of resources in order to optimize operational costs.
---
> [CEN-1008] Add HPA for microservice transaction error manager

- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
This PR enables [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) for the bpdmsrankingprocessor deployment.
- HPA for deployment bpdmsrankingprocessor
This change allows us to move away from a fixed allocation of resources in order to optimize operational costs.
---
> [CEN-1010] Add HPA for microservice ranking processor

- src/env/prod/terraform.tfvars
This PR proposes to create a firewall rule on prod DBMS to grant access to PDND
- New firewall rule to allow access from PDND outbound address
In a couple of weeks BPD will reach its end of life. In order to reduce costs, PDND should read data from master dbms, since the replicas will be deleted 
---
> [CEN-1066] Grant PDND access on master DBMS in prod

- src/k8s/rtd_configmaps.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/variables.tf
This PR introduces a new config map defining the execution environment for the service RTD transaction filter (a.k.a. batch acquirer)
Added configmap definition and subscription variables for DEV environment
The configmap is needed in order to run the transaction filter service on DEV environment
---
> [CEN-1045] Add configmap for RTD transaction filter service

- src/env/prod/terraform.tfvars
This PR proposes to scale down the production DBMS to 2 vcore (10 GB RAM)
- Set the Prod DBMS SKU to `GP_Gen5_2`
- Set Alarm Threshold on active connections to 116
The goal of this PR is further reduce infrastructure cost
---
> [CEN-1093] Scale Down Prod DBMS SKU to 2 V-Core

- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
This PR proposes to set the JVM allocated memory to the Batch Acquirer to 4GB, as [suggested in the documentation](https://github.com/pagopa/rtd-ms-transaction-filter/blob/1.0.2/README.md#logging-configurations), in the DEV environment.
Added JAVA_TOOL_OPTIONS parameter to the rtdmstransactionfilter configmap in the DEV environment
This change aligns the actual DEV configuration with the suggested one from the software documentation
---
> [CEN-1082] set JAVA_TOOL_OPTIONS on RTD transaction filter DEV

- src/api.tf
- src/outputs.tf
- src/redis_cache.tf
This PR proposes to destroy the Redis Cache and detach it as APIM external cache.
- Remove resource `module.redis`
- Set to `null` redis connection string in APIM definition
Under the current load, APIM uses only 500 MB of external cache, so it could rely on its internal cache, which is as big as 5 GB
---
> [CEN-1097] Destroy external redis cache and detach it from APIM

- src/psql/migrations/PROD-CSTAR/bpd/V10__optimization_delete_citizen.sql
This PR proposes to add an index in table `bpd_winning_transaction_transfer` on `fiscal_code_s` column to speed up the following query executed during user cancellation
`delete from bpd_winning_transaction_transfer where fiscal_code_s=$1`
- New index
This PR is a tentative to speed up a query which is executed for user cancellation.
---
> [CEN-1103] Add Index on fiscal code to winning transaction transfer

- src/k8s/rtd_configmaps.tf
- src/k8s/rtd_secrets.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
This PR enable the encryption of output file produced by the Batch Acquirer using a PGP key.
- Added a secret to safely store the key
- Enabled encryption by setting ACQ_BATCH_TRX_LIST_APPLY_ENCRYPT to true and ACQ_BATCH_INPUT_PUBLIC_KEYPATH to the path where the key will be available inside the pod
We need to test this capability in our DEV environment
---
> [CEN-1084] Enabled encryption of file produced by RTD transactionfilter

- src/api/fa_mock/swagger.json.tpl
- src/api/fa_register_transaction/openapi.json.tpl
- Add contractId in FaTransaction and Mock interfaces to link POS transaction to correct provider
This change is necessary to extract correct provider during acquirer transaction's injection process and send invoice request
---
> [CEN-1134] Add contractId in API's input body

- src/api.tf
- src/api/bpd_io_award_period/original/findAllUsingGET_close_cashback_policy.xml.tmpl
- src/api/bpd_io_award_period/v2/findAllUsingGET_close_cashback_policy.xml.tmpl
This PR proposes a couple of changes to align terraform code to the new revision of the award_period api policy created via azure portal
- update the revision of the policy of api award_period to the one created to cose the cashback
- align the policy definition in terraform code to the one created via portal
This PR is needed to align the revision of the policy of award_period api to the one created via azure portal to close the cashback. 
This PR is dependent on the following PR
https://github.com/pagopa/azurerm/pull/148
---
> [CEN-1236] Align policy of api award_period to changes made via azure portal

- src/env/dev/terraform.tfvars
This PR updates the node size for the 'default' node pool of the DEV AKS cluster from 'Standard_DS2_v2' to 'Standard_B4ms'
Set value for variable 'aks_vm_size' on DEV subscription
The previous node size wasn't providing enough RAM on a single node to satisfy the workload requirements.
---
> [CEN-1275] Increase default node pool node size to Standard_B4ms

- src/.terraform.lock.hcl
- src/database.tf
- src/dns_private.tf
- src/env/dev/terraform.tfvars
- src/env/prod/terraform.tfvars
- src/env/uat/terraform.tfvars
- src/main.tf
- src/network.tf
- src/outputs.tf
- src/variables.tf
This PR proposes to add a new DBMS (Postgres Flexible Server) to support FA application
- new Postgres Flexible Server
- new private DNS zone
- new delegated subnet dedicated to the new Postgres Flexible Server
- update the azurerm provider to version 2.92.0 (required to support geo-redundancy)
This change is required to get many advanced feature of postgres, like high availability, a better lifetime support and a centralized connection pooling
---
> [CEN-1303] Add postgres flexible server to support FA application

- src/k8s/fa_configmaps.tf
- src/k8s/fa_secrets.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
This PR proposes a way to add credentials to call ADE api to verify a vat number in `fa-ms-invoice-manager` micro-service environment
- Update the list of secrets to be read form key vault
- Create a new k8s secret
- Update fa-ms-invoice-manager environment
This PR is required to be able to verify the correctness/existence of a vat number using ADE api.
---
> [CEN-1311] Add secrets to call ADE "verify vat number" API

- src/k8s/fa_secrets.tf
- src/k8s/locals.tf
This PR proposes to modify the connection string to `fa` database, now hosted on Postgres Flexible Server
- New terraform local variable which contains the DBMS private endpoint hostname
- Fix the k8s secret which contains the connection string
This PR is required to migrate FA to a Flexible Server DBMS
---
> [CEN-1252] Modify Postgres connection string to flexible server

- src/k8s/fa_configmaps.tf
- src/k8s/fa_secrets.tf
- src/psql/migrations/DEV-CSTAR/fa/U1__fa_drop_schemas_and_tables.sql
- src/psql/migrations/DEV-CSTAR/fa/U2__fa_drop_constraints.sql
- src/psql/migrations/DEV-CSTAR/fa/V1__fa_create_schemas_and_tables.sql
- src/psql/migrations/DEV-CSTAR/fa/V2__fa_create_contraints_and_privileges.sql
This PR proposes to modify 
- config-maps and secrets in `fa` k8s namespace, plus 
- Postgres Flexible Server migrations 
to support deployment of `cstariobackendtest` micro-service in `fa` k8s namespace
- A new configmap in `fa` k8s namespace
- A new secret in `fa` k8s namespace
- A new migration to create the schema `fa_mock` in the Postgres Flexible Server
In order to migrate FA system in UAT, the micro-service `cstariobackendtest` should be moved in `fa` k8s namespace and should use the new DBMS for its data
---
> [CEN-1321] Modify configmaps, secrets and migration to support mock microservice

- src/psql/migrations/UAT-CSTAR/bpd/U22__bpd.alter_citizen_drop_opt_in_status.sql
- src/psql/migrations/UAT-CSTAR/bpd/V22__bpd.alter_citizen_add_opt_in_status.sql
- Add opt_in_status_n in BPD_CITIZEN table
This change is required to add new column in BPD_CITIZEN table
---
> [CEN-1315] add optInStatus in citizen table UAT

- src/api.tf
- src/api/rtd_csv_transaction/openapi.json.tpl
This PR renames the prefix "/cstar" to "/rtd" for the endpoints exposed under the API CSV Transaction, and accordingly the prefix for blobstorage containers created by the /rtd/sas endpoint.
Renamed cstar to rtd both on endpoint path and container prefix
The RTD naming is more appropriate given the kind of transactions that the endpoint and the generated containers will handle.
---
> [CEN-1356] Rename cstar prefix to rtd

- src/env/dev/terraform.tfvars
- src/env/prod/terraform.tfvars
- src/env/uat/terraform.tfvars
- src/psql/flyway.sh
- src/psql/migrations/PROD-CSTAR/bpd/U11__bpd.alter_citizen_drop_opt_in_status.sql
- src/psql/migrations/PROD-CSTAR/bpd/V11__bpd.alter_citizen_add_opt_in_status.sql
This PR proposes to modify production DB to implement payment instruments opt-in status. The feature has been tested in UAT and has proven to be backward compatible with existing version of APP IO
- New column in citizen table to store the citizen state in the card opt in use case
- this PR allows to manage the payment instruments opt-in use case
---
> [CEN-1365] Modify BPD production DB to implement opt in status

- src/api/bpd_io_citizen/v2/findUsingGET_policy.xml
- src/api/bpd_io_citizen/v2/openapi.json.tpl
- Add optInStatus in request body of PUT citizen endpoint
- Add optInStatus in response body of GET citizen endpoint
- Mock response in GET citizen with default optInStatus value
Those changes are required to handle new property optInStatus in Citizen API
---
> [CEN-1314] add optInStatus in citizen API

- src/dns_private.tf
- src/env/dev/terraform.tfvars
- src/env/uat/terraform.tfvars
The APIM internal hostname as defined in the internal DNS zone is not uniform across the various subscriptions at the moment. This PR proposes to adopt a uniform naming for it.
- add customisation of internal zone domain for DEV env
- change internal APIM hostname from 'cstar-X-apim' to 'apim' for all subscriptions
Adopting a consistent naming scheme is beneficial.
---
> [CEN-1405] Uniform internal APIM endpoint across subscriptions

- src/api.tf
- src/security.tf
This PR adds a new custom domain matching the internal DNS APIM name. This new domain allows to serve requests originated from internal services without the necessity of routing the requests through the publicly exposed endpoint.
- add a self-signed certificate for internal use only
- add a new custom domain registered on the internal DNS name of the APIM
- Allow internal applications to communicate to the APIM without relying on the publicly accessible URL.
---
> [CEN-1404] Add private custom domain

- src/env/dev/terraform.tfvars
- src/events.tf
- src/variables.tf
This PR proposes to add an `event grid` subscription to route event to an event hub, thus allowing to use _classic_ `k8s` microservices to implement _reactive_ systems.
- A new event hub to host platform events
- A new event grid subscription capable of routing events the the new event hub
This PR is needed to implement reactive workflows to ingest acquirer transactions
---
> [CEN-1361] Add event grid subscription and link it to event hub

- src/api.tf
- src/api/rtd_csv_transaction/create-sas-token-policy.xml.tpl
This PR modify the "RTD CSV Transaction" and "RTD CSV Transaction Decrypted" to explicitly communicate to the storage account via private endpoint. At the moment the APIs are already using the private endpoint but relying on the fact the public endpoint is transparently resolved with the internal IP by the private network internal DNS.
- explicitly set blob storage name to the private FQDN
- Referring to the storage via public endpoint is misleading and could possibly pose security concerns in case of misconfiguration
---
> [CEN-1406] Use only storage private endpoint in RTD CSV Transaction APIs

- src/api_rtd.tf
This PR proposes to fix the policy of operation `get-hashed-pans`
- Remove conditional to set host to `prod.cstar.pagopa.it` in production
This PR solves a failure in TLS handshaking
---
> [CEN-1431] Fix get-hashed-pans policy

- src/api/fa_hb_payment_instruments/enrollmentUsingPUT_Card_policy.xml.tpl
This PR proposes to improve observability of PM responses when a new payment instrument in enrolled.
- Modify apim policy of API PUT card in Payment Instruments.
When an enrollement of a new payment instrument fails, the client doesn't know if the error is from CSTAR or PM.
---
> [CEN-1538] Add PM response body when Card enrolling fails

- src/k8s/bpd_ingress.tf
- src/k8s/fa_ingress.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
This PR adds a rule to address cstariobackendtest in FA context and change invoice manager environment (only in DEV and UAT) to point to the AdE mock API.
- Edit ingress to route cstariobackendtest in fa namepace
- Remove ingress rule that routes requests to cstariobackendtest  in bpd namespace
- Edit configmaps of DEV and UAT to change AdE URL to mock service
To carry out some loads tests it's necessary mocking AdE endpoints instead of use real endpoint.
> [CEN-1558] add rule to address cstariobackendtest in FA context

- src/env/dev/terraform.tfvars
This PR proposes to add a queue to receive resolved couples (PAN; PAR) from TKM sub-system.
- New topic `tkm-write-update-token` in BPD EventHub namespace. The BPD namespace will be converted in the foreseeable near future to become the RTD namespace
After querying different card schemes (AMEX, VISA, MASTERCARD, ..) TKM subsystem can associate unknown TokenPANS to their PAR. Such associations must be transmitted to CSTAR via a dedicated queue.
---
> [RTD-23] Add tkm update queue

- src/api/cdc/openapi.io.yml.tpl
Update CdcC IO Swagger
- Remove year in POST response when it returns 400
year, in case of failure, doesn't convey any useful information
---
> [CDC-65] Remove year in POST response when it returns 400

- src/k8s/rtd_secrets.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
- src/k8s/variables.tf
This PR proposes to store in a aks secret the mongo DB connection string
- new key vault secret containing mongodb connection string
- new k8s secret referencing the key vault secret
This PR enables microservices to use a non relational datastore
---
> [RTD-112] Create secret containing mongo DB connection string

- src/k8s/rtd_ingress.tf
This PR propose the addition of a mapping on the k8s ingress.
Through this we can exposing an endpoint for the new micro-service rtdmsfileregister.
- add a mapping to rtd ingress
We want to internally expose the micro service in order to assess the proper functioning of the DB.
---
> [RTD-113] Add ingress mapping for RTD file register micro-service

- src/api/cdc/get-stato-beneficiario_policy.xml
- src/api/cdc/policy.jwt.xml.tpl
This PR proposes to fix caching policy by using as a key the bpd token.
- cache key is now the bpd token + endpoint name since the jws token is modified at each request so results always in a cache miss
- change the logical condition to cache
This PR is motivated by the fact that caching can't work if the key changes at each and every request
---
> [CDC-29] update caching policy to use as a key the bpd-token

- src/env/dev/terraform.tfvars
This PR proposes to add an ad hoc consumer group for micro-service file register in the rtd-platform-events Event Hub.
- add file register consumer group in rtd-platform-events.
This change is required in order to make the file-register capable of consuming events, enabling its queue interface.
---
> [RTD-164] add file register consumer group in DEV

- src/README.md
- src/api/rtd_senderack_download_file/azureblob_policy.xml
- src/api/rtd_senderack_download_file/openapi.json.tpl
- src/api_tae.tf
This PR adds an API to download the sender ade ack files from a blob storage container by filename.
- Add new api with policy and swagger
The batch service must download the sender ade ack files. The filename list is retrieved from `/rtd/file-register/sender-ade-ack` and downloaded with the new api `/ade/{filename}`.
---
> [TAE-44] Add API to download sender ade ack files

- src/database.tf
- src/network.tf
This PR proposes to allow access to Mongo DB from ADF subnet
- Modify the list of MongoDb allowed subnets to include ADF subnet
In order to create an ADF pipeline, the Linked Services should be able to access sources and sinks. MongoDB can be both a source and a sink so ADF should be allowed to access it.
---
> [TAE-52] Enable Mongo DB access from ADF subnet

- src/README.md
- src/api/rtd_sender_api_key_check/openapi.yml
- src/api/rtd_sender_api_key_check/policy.xml
- src/api_rtd.tf
This PR proposes the addition of an API that allows senders to test their RTD API validity.
- add the new module rtd_sender_api_key_check that model the behaviour of the API Key check endpoint
As second step of sender onboarding, we want to provide an endpoint that allows the client to test for its API Key validity.
The module uses the feature flag for batch service endpoints.
---
> [RTD-135] API to test rtd api key

- src/pipelines/ackIngestor.json
- src/tae_pipeline.tf
This PR proposes to add the pipeline RunId as field when acks are ingested.
- New additional column in dataset representing ade acks and related mapping
This PR ensures that acks ingested in the same pipeline can be recovered at a later time
---
> [TAE-83] Add pipeline RunId as field to ingested aggregates acks

- src/README.md
- src/tae_datasets.tf
This PR proposes to add a new dataset to represent wrong fiscal codes
- New dataset for wrong fiscal codes
This dataset solves the problem of representing worng fiscal codes to be sent to senders
---
> [TAE-82] Add dataset for wrong fiscal codes

- src/README.md
- src/database.tf
- src/k8s/rtd_secrets.tf
- src/k8s/scripts/setup.sh
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
This PR proposes to add MongoDB connection URI to secrets.
- add MongoDB connection URI to secrets (mongo-credentials)
- remove MongoDB key from secrets
This change allows file register to connect to MongoDB.
---
> [TAR-97] Add mongo connection URI to secrets

- src/k8s/README.md
- src/k8s/rtd_configmaps.tf
- src/k8s/rtd_secrets.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
- src/k8s/variables.tf
This PR add configuration map for `rtd-enrolled-payment-instrument` microservice
- added kafka secret with consumer policy
- added `rtd-enrolledpaymentinstrument` config maps which specify the mongo db name
---
> [RTD-305] Add k8s config to enrolled-payment-instrument ms

- src/domains/idpay-common/01_keyvault_0.tf
- src/domains/idpay-common/README.md
- src/domains/rtd-common/01_keyvault_0.tf
- src/domains/rtd-common/README.md
- src/domains/tae-common/01_keyvault.tf
- src/domains/tae-common/README.md
- src/key_vault_access_policy.tf
- improve access policy to for idpay and rtd for developer
- added externals to idpay and rtd DEV
The developer wan't able to see the UAT and PROD kv
---
> feature: Allow developers to see kv in uat

- src/api/rtd_csv_transaction/create-sas-token-policy.xml
- src/api_rtd.tf
- change the endpoint policy to translate the api key in sender code
- modify the naming of the container based on the hash of the sender code
This change allows us to refer to a sender's container with the hash of the sender code.
This is easier compared to the hash of the api key.
Targets:
- module.rtd_csv_transaction[0].azurerm_api_management_api_operation_policy.api_operation_policy
---
> [TAE-88] Hash Sender Code for container name

- src/domains/tae-app/08_pipeline.tf
- Change suffix path in aggregate ingestor trigger
This PR allows the pipeline to ingest aggregates with new naming convention.
Target:
- azurerm_data_factory_trigger_blob_event.acquirer_aggregate
---
> [TAE-164] Modify aggregates ingestor trigger pattern

- src/core/env/prod/terraform.tfvars
- src/domains/tae-common/env/prod/backend.ini
- src/domains/tae-common/env/prod/backend.tfvars
- src/domains/tae-common/env/prod/terraform.tfvars
This PR proposes to migrate comsos (both mongo and sql api) to production.
Cosmos SQL API supports Data Factories. Cosmos Mongo API supports TAE/RTD microservices
- New instance of Cosmos DB SQL API
- New Instance of Cosmos DB MONGO API
- Cosmos subnets
- Private endpoints subnet
These changes are required to support TAE in production
---
> [TAE-172] Migrate cosmos in prod

- src/k8s/rtd_configmaps.tf
This PR proposes to increase the decrypter consumer timeout from 10 minutes to 2 hours.
- Changed config map of micro service decrypter
In order to avoid the consumer timeout during the file elaboration it is required to increase the `max.poll.interval.ms` through the config map of micro service decrypter. 
---
> [RTD-433] increase the decrypter consumer timeout

- src/core/README.md
- src/core/tae_storage.tf
This PR proposes to create the container `tmp` in `cstarblobstorage`, which it is utilized by the ade ack ingestor pipeline.
- Blob storage container creation
The ade ack ingestor pipeline needs a container to temporarily create the ade ack files and then copy though a copyData activity to generate the `blobCreated` event.
---
> [RTD-438] add tmp container on blob storage

- src/domains/tae-app/08_pipeline.tf
- src/domains/tae-app/99_variables.tf
- src/domains/tae-app/README.md
- src/domains/tae-app/env/dev/terraform.tfvars
- src/domains/tae-app/env/prod/terraform.tfvars
- src/domains/tae-app/env/uat/terraform.tfvars
This PR proposes to reduce the frequency of Ack Ingestor Pipeline to 1/hour
- For testing purposes, Ack Ingestor frequency was set to 4/hour. In this PR we propose to reduce it to 4/hour
This PR is motivated by the fact that input for ade ack ingestor batch are generated with a frequency of 1 file / hour
---
> [RTD-435] Reduce Ack Ingestor Frequency from 4/hour to 1/hour

- src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
This PR proposes to update the conversion map between fake abi and fiscal codes of the acquirers.
- Updated APIM policy
The batch service must download the correct conversion map.
---
> [RTD-439] update conversion map abi to fiscalCode

- src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
This PR proposes to add the ICARD mapping to the abi-fiscalCode conversion map.
- Update policy
The abi-fiscalcode conversion map needs to be updated with the new acquirer.
---
> [RTD-446] add ICARD to conversion map abi-fiscalCode

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
- src/domains/tae-app/scripts/create_tables.dexp
This PR proposes to create two tables in TAE DB of Data Explorer: the first, named `Aggregates`, is meant to log aggregates  by Senders, the second, named `Acks`, is meant to log acks from AdE
- New script to create Aggregates and Acks tables in Data Explorer
Implement application metrics and dashboards
---
> [TAE-187] Add script to create tables in TAE db in Data Explorer

- src/core/env/dev/terraform.tfvars
- changed cird for dev dns forwarder
The old cird for dns forwarder has the ip already used, this thing cause the vpn dev to stop working.
To fix the problem we move the dev cird to other range
---
> fix: VPN dev problem - changed range cird for dev dns forwarder

- src/domains/tae-app/07_datasets.tf
- src/domains/tae-app/pipelines/ackIngestor.dataflow
This PR proposes to insert the pipeline RunID in sender ade ack name to ensure uniqueness.
- specify folder path in intermediate dataset.
- concatenate pipeline RunID in sender ade ack name
This change allows files with common sender code, acquirer ID and processing date to be distinguished by pipeline runid.
This prevents override during copy in sender-ade-ack container.
-target=azurerm_data_factory_pipeline.aggregates_ingestor 
-target=azurerm_data_factory_pipeline.ack_ingestor
---
> [RTD-511] Fix adeack name uniqueness

- src/core/rtd_database.tf
This PR adds indexes over `apiKey` and `senderCodes` key to improve query performance by rtd-ms-sender-auth.
- apiKey as index and unique
- senderCodes as index
Cause mongo db documents are retrieved by `apiKey` using it as index should improve query performance. Furthermore `senderCodes` is used to check if a sender code is already associated to another apiKey, indexing it should improve query.
Creating indexes on existing collection with documents is prohibited. So these actions need to be performed on each environment to successfully migrate the collection:
- dump collection
- create indexes using terraform
- restore collection
---
> [RTD-520] Added indexes to senderauth collection

- src/domains/idpay-app/01_keyvault.tf
- src/domains/idpay-app/08_k8s_configmaps.tf
- src/domains/idpay-app/99_variables.tf
- src/domains/idpay-app/README.md
- src/domains/idpay-app/env/dev/terraform.tfvars
- src/domains/idpay-app/env/uat/terraform.tfvars
- src/k8s/README.md
- src/k8s/rtd_configmaps.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
- src/k8s/variables.tf
This PR adds config map as a producer for rtd-enrolled-pi eventhub. The config map includes partitionCount and partitionKey expression.
- added partitionCount and partitionKey configmap to idpay domain
- added configmap to old rtd k8s cluster
This solve concurrency issue over rtd enrolled payment instrument microservice by design. Every producer produce to a specific partition this allows the same consumer to process the same set of events.
Applied to "old" rtd k8s and to idpay domain
---
> [RTD-539] Enrolled pim producer config

- src/core/api/rtd_senderack_filename_list/policy.xml.tpl
- src/core/api_rtd.tf
This PR remove technical debt due to missing ingress template variable inside `senderack-filename-list` policy
---
> [RTD-582] Added ingress template to sender-ack-filename-list endpoint

- src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
This PR proposes to fix Telepass Pay fiscal code with a missing leading 0.
```
--target="module.rtd_fake_abi_to_fiscal_code[0].azurerm_api_management_api_policy.this[0]"
```
---
> [RTD-646] Fix TPAY1 FC

- src/core/api/rtd_senderack_download_file/azureblob_policy.xml
This PR adds authorization call to sender-auth before download an ade ack file.
---
`-target="module.rtd_senderack_download_file"`
> feat: [RTD-592] Add sender-auth authorization call to download ack

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/domains/idpay-app/01_keyvault.tf
- src/domains/idpay-app/99_variables.tf
- src/domains/idpay-app/README.md
- src/domains/idpay-app/env/dev/terraform.tfvars
- src/domains/idpay-app/env/uat/terraform.tfvars
This PR create a revoke card queue where PIM is the producer and various application (ID PAY) are consumers.
- adds `rtd-revoke-pi` queue to DEV, UAT and PROD environment. (PROD under fa namespace due to limits of rtd evh)
- push to idpay keyvault the connection string as queue consumer 
---
Inside `core` folder
`-target="module.event_hub"` for DEV and UAT
`-target="module.event_hub_fa_01"` for PROD -> due to full PROD eventhub namespace
Inside `idpay-app`:
`-target=azurerm_key_vault_secret.revoked_pi_consumer_connection_uri`
> feat: [RTD-721] Added rtd revoke queue

- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
Fixed a variable name inside object with FA autoscaling specs (only UAT subscription)
- Fixed a variable name inside object with FA autoscaling specs (only UAT subscription)
It was necessary to make this fix because otherwise autoscaling on the "famsenrollment" microservice would not work
> fix: [CSFA-72] Error in "fa_autoscaling_specs" UAT variable

- src/k8s/README.md
- src/k8s/rtd_secrets.tf
- src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
- src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
- src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
- src/k8s/variables.tf
This PR adds the producer connection string to k8s to be used by PIM to produce revoke events for applications
- added secret to k8s
- fix missing default for fa_autoscale
---
> chore: [RTD-722] Add revoke producer k8s secret

- src/k8s/rtd_ingress.tf
Enable k8s ingress for enrolled payment instrument manager
---
> fix: pim missing ingress

- src/k8s/rtd_configmaps.tf
This PR proposes to add decrypter role name to its config map.
This change allows us to improve decrypter monitor on Application Insights.
```
--target="kubernetes_config_map.rtddecrypter[0]"
```
---
> feat: [RTD-764] Add decrypter role name

- src/k8s/rtd_secrets.tf
This PR fixs wrong connection string to `rtd-revoked-pi` queue which is created inside fa eventhub ns
---
> fix: fix revoke eventhub connection string fa

- src/domains/tae-app/00_monitor.tf
This PR proposes to adapt existing alerts in order to send an email to Zendesk as action. 
- add Zendesk action group
- modify display name to include #ACQ string
With this change we can notify Operations' Zendesk also for existing alarms.
---
> feat: [RTD-812] Add Zendesk action to existing alerts

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
Thi PR proposes to add an alert that triggers whenever a file is created in ade/error directory through SFTP.
- add alert
- update readme
With this change we can monitor the upload of a file in ade/error and take action contacting Agenzia delle Entrate.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.created_file_in_ade_error[0]"
```
---
> feat: [RTD-703] Add file creation in ade/error alert

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever a sender receive an error during blob upload on /pagopastorage.
- add alert
- update doc
With this change we can monitor failures returned by the application gateway to the senders during blob upload.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.sender_fails_blob_upload[0]"
```
---
> feat: [RTD-840] Add alert for failed blob upload

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever at least one request to remove a file from ade/ack is issued through SFTP.
- add alert
- update doc
With this change we can monitor events of issued remove command on a file in ade/ack.
Only SFTP commands are monitored.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.ade_removes_ack_file[0]"
```
---
> feat: [RTD-702] Add alert on remove ade ack file

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever at least one input file cannot be decrypted.
- add alert
- update doc
With this change we can be notified through Slack and email whenever a file cannot be decrypted.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.failed_decryption[0]"
```
---
> feat: [RTD-843] Add failed decryption alert

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever at least one input file contains no data once decrypted.
- add alert
- update doc
With this change we can be alerted if an empty file is decrypted.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.no_data_in_decryted_file[0]"
```
---
> feat: [RTD-844] Add alert whenever there is no data in decrypted file

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever at least one input file has a wrong name format (e.g. malformed date).
- add alert
With this change we can monitor failures occurred before decryption step.
---
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.wrong_name_format[0]"
```
> feat: [RTD-852] Wrong encrypted name format alert

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever at least one ack ingestor pipeline fails.
- add alert
With this change we can monitor granularly the failure of a specific pipeline.
Troubleshooting activity is aimed and facilitated.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.ack_ingestor_failures[0]"
```
---
> feat: [RTD-740] Add ACK ingestor pipeline failure alert

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever at least one aggregates ingestor pipeline fails.
- add alert.
With this change we can monitor granularly the failure of a specific pipeline.
Troubleshooting activity is aimed and facilitated.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.aggregates_ingestor_failures[0]"
```
---
> feat: [RTD-739] Add aggregates ingestor failure alert

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever at least one PUT request on /pagopastorage receive 401 response.
- add alert
With this change we can granularly monitor responses to Batch Service given by APIM during upload operation.
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.sender_fails_blob_upload_unauthorized[0]"
```
---
> feat: [RTD-897] Add unauthorized failed upload alert

- src/k8s/rtd_ingress.tf
This PR add pi event processor mapping to ingress. This is useful to test it by using rest api
---
`-target="kubernetes_ingress_v1.rtd_ingress"`
> fix: Added missing pi event processor ingress mapping

- src/domains/tae-app/00_monitor.tf
This PR proposes to exclude manual trigger from pipeline failure query for alerts.
- add a condition in query alert
With this change we avoid being alerted for pipeline runs manually triggered.
We take for granted the presence of an operator in those situations, thus an alert is superfluous.
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.aggregates_ingestor_failures 
-target=azurerm_monitor_scheduled_query_rules_alert_v2.ack_ingestor_failures
```
---
> fix: [RTD-920] Exclude manual trigger from pipeline failure query for alerts

- src/domains/tae-app/00_monitor.tf
Adapt sender auth alert to query for 401 instead of 404.
- change status code in alert query
We needed this change to adapt alert to new result code returned by sender auth in case of Internal ID miss.
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.sender_auth_missing_internal_id
```
---
> fix: [RTD-1091] Change result code in sender auth alert query

- src/core/api/azureblob/azureblob_authorizative_policy.xml
This PR proposes to add `If-None-Match` header in the policy of encrypted file upload endpoint. 
- add header
With this change we can check if a blob with the same name of the one that is attempted to be uploaded is already present
In case of file name already present in target blob a 409 is returned to the client.
```
-target=module.api_azureblob
```
---
> feat: [RTD-644] Add header to grant file uniqueness in blob upload policy

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever a request to obtain SAS token for either RTD or TAE fails.
- add alert
With this change we can be notified whenever a call to obtain a SAS token fails.
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.failure_on_sas_token_endpoint
```
---
> feat: [RTD-858] Add alert on SAS failure

- src/core/99_outputs.tf
- src/core/README.md
- src/domains/rtd-app/08_k8s_configmaps.tf
- src/domains/rtd-app/README.md
- src/domains/rtd-app/env/prod/terraform.tfvars
- src/domains/rtd-common/01_keyvault_external_database.tf
- src/domains/rtd-common/README.md
This PR adds config maps related to rtd-ingestor to new aks.
The `rtd_internal_api_product_subscription_key` secrets is copied to new keyvault by using terraform core folder `outputs`.
---
> chore: [RTD-1069] Add configmap to new aks for ingestor

- src/core/api/rtd_senderack_correct_download_ack/policy.xml
- src/core/api/rtd_senderack_download_file/azureblob_policy.xml
- src/core/api/rtd_senderack_filename_list/policy.xml.tpl
- src/core/api_rtd.tf
- src/core/api_tae.tf
This PR updates APIM policies which forward request to file-register by using new aks internal address (https)
---
`-target="module.rtd_senderadeack_filename_list" -target="module.rtd_senderack_correct_download_ack" -target="module.rtd_senderack_download_file"`
> chore: [RTD-1077] update apim file-register address to new aks ingress

- src/core/README.md
- src/core/api_product/rtd_api_internal/policy.xml.tpl
- src/core/api_rtd.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/variables.tf
This PR adds ip range filter to allow requests from new aks cluster
---
> fix: [RTD-1173] Add ip range to filter in aks requests to internal api

- src/domains/tae-app/00_monitor.tf
This PR proposes to fix an overlapping in alerting that occurs when a 409 is returned during an upload request.
- modify and clarify alert query.
With this change we avoid triggering 2 alerts with the same condition.
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.sender_fails_blob_upload
```
---
> fix: [RTD-1182] Exclude 409 from failed upload alert

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert on 409 status code given by APIM. The status code is given by Storage Account when a file is being uploaded with the same name as one already present.
- add aleret
With this change we can detect tentatives of duplicate uploads.
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.pgp_file_already_present_on_storage_account
```
---
> feat: [RTD-1118] Add alert on conflicting file submission

- src/domains/idpay-common/README.md
- src/domains/tae-app/env/uat/terraform.tfvars
This PR proposes to structurally enable ack ingestor trigger in UAT.
- enable trigger
- increase interval to 120 minutes
We want process ACK sent by AdE in UAT like in PROD environment. Schedule and interval must match the production one.
```
-target=azurerm_data_factory_trigger_schedule.ade_ack
```
---
> chore: [RTD-1227] Enable ACK ingestor trigger in UAT

- src/domains/tae-app/00_monitor.tf
This PR proposes to structurally disable the alert that triggers whenever a sender doesn't send for more than 2 days.
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.sender_doesnt_send
```
---
> fix: [RTD-1155] Disable alert on sender doesn't send

- src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
- src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl
- src/domains/idpay-common/.terraform.lock.hcl
- src/domains/idpay-common/03_database.tf
- src/domains/tae-common/04_datafactory.tf
- src/domains/tae-common/README.md
Added group_user_whitelist collection to IDPay database. The collection features two additional non-unique indexes (apart from the default unique _id): one on the groupId field, and another one on the userId field
This lookup collection has been added in order to prevent large (about > 90K userId) whitelists of userId strings to be written on a single document of the group collection, causing a 413 error, and a subsequent exception. 
---
> feat: [IDP-177] Adding group/user lookup table to terraform

- src/domains/idpay-app/README.md
- src/domains/tae-common/03_database.tf
This PR proposes to ignore the change on max throughput for cosmos aggregates resource. As adopted practice, it's suggested to change the max throughput setting via portal.
- Add snippet to ignore max throughput setting on aggregates db
---
> chore: [RTD-1302] ignore changes on aggregates db max throughput

- src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
- src/core/api_rtd.tf
This PR proposes to add Euronet technical sender code (EURON) to Fiscal Code mapping.
- add mapping to the endpoint exposed to the Batch Service.
This change allow Euronet to use their technical ABI and grants AdE the corresponding Fiscal Code if the same value is used in acquirer code field.
```
-target=module.rtd_fake_abi_to_fiscal_code
```
---
> feat: [RTD-1330] Add EURON fiscal code mapping

- src/core/api/rtd_abi_to_fiscalcode/policy.xml.tpl
This PR proposes to add Uber technical sender code (UBER1) to Fiscal Code mapping.
- add mapping to the endpoint exposed to the Batch Service.
This change allow Uber to use their technical ABI and grants AdE the corresponding Fiscal Code if the same value is used in acquirer code field.
```
-target=module.rtd_fake_abi_to_fiscal_code
```
---
> feat: [RTD-1331] add UBER1 to fiscal code mapping

- src/core/env/dev/terraform.tfvars
It was changed the number of partitions for rtd-platform-events queue and it was added a capability to cosmos db to enable server side retry.
---
> chore: [RTD-1305] upgrade rtd-platform-events queue partitions and add server side retry cosmos db

- src/domains/idpay-common/env/dev/terraform.tfvars
- src/domains/idpay-common/env/prod/terraform.tfvars
- src/domains/idpay-common/env/uat/terraform.tfvars
The provider 2.99 of Azure will destroy and create the cosmosdb_account, while the change performed doen't require it (new versions also allow to change this without destroy).
Please, apply the change manually, next verify that planning on the merge will not see any change on the infrastructure
To apply manually you have to:
1. open the Azure portal
2. locate and open the _cstar-[ENVSHORT]-idpay-mongodb-account_ resource
3. go to Features blade
4. Enable "Server Side Retry"
*********
IDP-367 added capability DisableRateLimitingResponses to cosmos
---
> feat: IDP-367 added capability DisableRateLimitingResponses to cosmos

- src/domains/tae-app/00_monitor.tf
This PR proposes to change the query used to alert on ade/error file deposit.
- remove temporary wrote table.
The creation of an empty file in SFTP skips the write step, thus the join on create/write/commit tables would result in no row to alert.
With this change we exclude the write step from the join. Now even the creation an empty file is alerted correctly.
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.created_file_in_ade_error
```
---
> fix: [RTD-1384] Fix deposit on ade/error alert

- src/core/api/azureblob/openapi.json.tpl
- src/core/api_rtd.tf
This PR proposes to update the OpenAPI of Blob Storage endpoint with PUT limit status codes.
- update OpenAPI file.
With this change we can provide users information about possible status codes returned by the endpoint.
```
-target=module.api_azureblob
```
---
> fix: [RTD-1402] Update OpenAPI with error status for rejected PUT

- src/domains/tae-app/00_monitor.tf
This PR proposes to remove 503 Service Unavailable from catch-all alert on pgp upload.
- exclude 503 from query results
- add status code to query results for clarity
With this change we avoid 2 alerts for the same event.
We also add additional information to the returned results.
Target: 
```
azurerm_monitor_scheduled_query_rules_alert_v2.sender_fails_blob_upload
```
The alert is updated:
---
> fix: [RTD-1476] Remove service unavailable from catch-all alert

- src/core/README.md
- src/core/api_rtd.tf
This PR proposes to terraform the log of Content-Length header.
- add API diagnostic to blob storage endpoint.
With this change we terraform a change done through Azure Portal.
With the log of the header we can be notified if something with the header is wrong.
Target: 
```
azurerm_api_management_api_diagnostic.blob_storage_api_diagnostic
```
No changes are proposed after resource import:
The header log is active:
---
> feat: [RTD-1475] Log Content-Length header in PGP upload endpoint

- src/domains/idpay-app/09_audit_log_storage.tf
- src/domains/idpay-app/09_refund_storage.tf
- src/domains/idpay-app/README.md
- src/domains/idpay-app/env/prod/terraform.tfvars
Setting private access to storage for PROD environment (DEV and UAT was already private)
-target=module.idpay_audit_storage -target=module.idpay_initiative_storage -target=module.idpay_refund_storage
Target: 
```
```
---
> fix: IDP-1260 setting PROD storage private

- src/domains/tae-app/pipelines/data-explorer-activities/duplicateAndInvalidateFlow.json
- src/domains/tae-app/pipelines/deleteAggregatesByTimestamp.json
This PR proposes to make invalidate flow pipeline idempotent.
- add a check whether a flow is already invalid
- add invalidation pipeline run id after ingestion pipeline run id to keep track of both
- add a cast to int on a pipeline parameter.
With this changes we avoid duplicating invalid flows if more than one invalidate flow pipeline is run with the same target flow.
Target: 
```
-target=azurerm_data_factory_pipeline.invalidate_flow
-target=azurerm_data_factory_pipeline.delete_aggregates_by_timestamp_pipeline
```
As shown in the following image a second run of invalidation cannot retrieve any row to invalidate:
---
> fix: [RTD-2306] Make invalidation pipeline idempotent

- src/domains/rtd-app/00_key_vault.tf
This PR proposes to change the source for cstarblobstorage-public-key from the core key vault (cstar-d-kv) to rtd domain key vault (cstar-d-rtd-kv) since it's only used by RTD and the private key is already on the destination keyvault.
The public key has been migrated from core kv to rtd kv.
batch service acceptance test
Target: 
```
-target=module.rtd_csv_transaction
```
---
> fix: read pgp public key from rtd key vault

- src/domains/rtd-common/00_network.tf
- src/domains/rtd-common/03_database.tf
- src/domains/rtd-common/04_eventhub.tf
- src/domains/rtd-common/README.md
This PR proposes to remove the references to old k8s snet in the rtd-common domain. Those references break the terraform plan since the resource does not exist anymore
Target: 
```
```
---
> fix: [RTD-2360] remove reference to old k8s snet

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/01_monitor_incident.tf
This PR sets alarm severity base on the following criteria : 
- Severity 4 -> alarm will be managed by Operation Team. 
- Severity 3+ -> alarm will be managed by IRT 
Moreover 
All alarms will be delivered to OpsGenie. OpsGenie will be our alarm control rooms.
action group related to ZenDesk has been removed from alarms ( but it's still available as resource)
Action group related to Slack is still available in order to monitor OpsGenie integration.
resource opsgenie has been moved, but it's not changed
Change action grouops and severity to alarms
Target: 
```
```
---
> fix: [RTD-2411] Alarms to opsgenie

- src/domains/rtd-app/08_k8s_configmaps.tf
This PR proposes to add a variable to the rtd-ms-file-reporter config map. The variable is needed to connect to the internal url of APIM
Target: 
```
-target=kubernetes_config_map.rtdfilereporter 
```
---
> fix: [RTD-2473] add apim internal host to config map reporter

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to evaluate logs and alert if a file is not processed by one of the components of TAE projects.
- add alert on files not evaluated by decrypter
- add alert on files not evaluated by aggregates-ingestor
With this change we can be alerted if some problem prevents a file to continue and we are not warned by other alerts.
Target: 
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.file-not-processed-by-decrypter -target=azurerm_monitor_scheduled_query_rules_alert_v2.file-not-processed-
by-aggregates-ingestor
```
---
> feat: [RTD-2556] Alert missing steps in TAE file processing

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add an alert that triggers whenever the decrypter can't get a file from storage account.
This also changes the "catch-all" alert.
Target: 
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.cannot_get_encrypted_file -target=azurerm_monitor_scheduled_query_rules_alert_v2.file-not-processed-by-decrypter
```
---
> feat: [TAE-215] Add alert when a GET of a pgp on decrypter fails

- src/domains/tae-app/00_monitor.tf
- src/domains/tae-app/README.md
This PR proposes to add a malformed checksum alert based on `rtd-ms-decrypter` logs.
- add alert
With this change we can be notified if a file contains a malformed checksum.
Target: 
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.malformed_checksum
```
---
> feat: [TAE-304] Add malformed checksum alert

- src/core-secrets/secret/prod/noedit_secret_enc.json
- src/core/README.md
- src/core/key_vault_0.tf
- src/core/observability.tf
**Description:**  
- Added OpsGenie action group for Azure monitoring in production.
- Configured webhook for enhanced alerting of Cstar Infra events.
- Secured webhook token management via key vault updates.
This integration improves alerting capabilities for infrastructure-related incidents, ensuring timely notifications.
---
> feat: [PAYMCLOUD-303] Add OpsGenie webhook integration for infrastructure alerts

- src/aks-platform/00_monitor.tf
- src/aks-platform/03_aks_0.tf
- src/aks-platform/99_locals.tf
- src/aks-platform/99_variables.tf
- src/aks-platform/README.md
- src/aks-platform/env/prod01/terraform.tfvars
1. Added support for OpsGenie alerts specific to the production environment.
2. Introduced a variable for the monitor resource group name.
3. Added a local value for the OpsGenie action group reference.
4. Updated alert configurations to include OpsGenie handling for the production environment.
5. Enabled alerts in the "prod01" configuration.
This change integrates OpsGenie alerting for better incident management in the production environment. It ensures critical alerts are routed appropriately to improve response times and incident resolution.
This change has been validated in the testing environment and the configurations were confirmed to work as intended
> feat: [PAYMCLOUD-304] Enable OpsGenie alerts for production environment for aks-platform

- src/core/README.md
- src/core/network.tf
- Removed `vnet_core_peering_secure_hub` module from `network.tf`.
The removal simplifies the codebase and reflects architectural changes. The `vnet_core_peering_secure_hub` module was deemed redundant and is no longer needed for managing secure hub VNet peering configurations.
> feat: [PAYMCLOUD-334] Remove vnet_core_peering_secure_hub module from network.tf

- src/domains/idpay-app/80_middleware_tools.tf
- src/domains/idpay-app/99_locals.tf
- src/domains/idpay-app/README.md
- src/domains/mil-app-poc/.terraform.lock.hcl
- src/domains/mil-app-poc/11_aks_middleware_tools.tf
- src/domains/mil-app-poc/README.md
- src/domains/rtd-app/80_middleware_tools.tf
- src/domains/rtd-app/99_locals.tf
- src/domains/rtd-app/README.md
- Removed deprecated `tls_checker` module usages across multiple domains.
- Cleaned up references to `domain_aks_hostname` where applicable.
- Updated Terraform lock file to reflect changes.
The `tls_checker` module is no longer in use and has been deprecated. Its removal simplifies the codebase and eliminates outdated references.
Target: 
```
```
N/A - No explicit testing provided for removal.
--- 
N
> feat: [PAYMCLOUD-311] Remove deprecated `tls_checker` module and references.

- src/core/app_gateway.tf
- Centralized handling of trusted client certificates using Terraform locals.
- Replaced hardcoded certificate lists with dynamic lists based on the environment, reducing redundancy and improving maintainability.
This change simplifies the management of client certificates, making the module easier to maintain and reducing the risk of errors when updating or adding new certificates.
The changes have been validated by running a `terraform plan` to confirm there are no unintended modifications. Unit testing and integration testing have been conducted to ensure functionality remains intact. 
[Link to test results](https://pagopa.atlassian.net/browse/RTD-XXXX) 
---
> chore: Refactor trusted client certificate management in App Gateway module

- src/core/99_locals.tf
- src/core/99_variables.tf
- src/core/README.md
- src/core/api.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
This PR proposes to add the bonuselettrodomestici.it domain into the allowed origins of apim global policy
Target: 
```
-target=module.apim
```
---
> feat: [EBE-73] add bonuselettrodomestici.it origin in apim policy
