pagopa/cstar-infrastructure

README.md
src/aks/README.md

- add aks readme
- update terraform modules readme 
---

Aks add readme

---

src/aks/bpd_ingress.tf
src/aks/ingress.tf
src/aks/namespaces.tf
src/aks/rtd_ingress.tf
src/aks/variables.tf

- add bpd_ingress, rtd_ingress rules
- set only one ingress controller in isolated namespace (ingress)
Ingress configuration
---

[#CEN-208] Add ingress configuration

---

src/aks/bpd_secrets.tf
src/aks/locals.tf
src/aks/secrets.tf
src/aks/terraform.sh

- add aks secrets management from keyvault
- move .terraform dir to root folder (required by terraform validate)
aks configuration
---

Aks add secrets

---

src/aks/bpd_secrets.tf
src/aks/secrets.tf
src/env/dev/terraform.tfvars

Remove not needed as per comment https://pagopa.atlassian.net/browse/CEN-323?focusedCommentId=12620
---

Remove not needed event hub

---

src/aks/bpd_configmaps.tf
src/aks/subscriptions/DEV-CSTAR/terraform.tfvars
src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
src/aks/subscriptions/UAT-CSTAR/terraform.tfvars
src/aks/variables.tf

- Refactor configmap to improve ux
- Add UAT and PROD configmaps
---

Refactor configmaps and add all envs

---

src/aks.tf
src/network.tf
src/outputs.tf
src/variables.tf

Allow to assing static outbound ips to aks

---

src/README.md
src/database.tf
src/outputs.tf
src/variables.tf

Allow to enable postgresql replica

---

src/database.tf
src/env/dev/terraform.tfvars
src/variables.tf

Expose geo backup and test replica in dev

---

src/README.md
src/aks.tf

Add  azurerm_role_assignment with AcrPull permission to AKS kubelets.
Needs "Microsoft.Authorization/roleAssignments/write" authorization to assign role
---

AcrPull AKS

---

src/aks/bpd_configmaps.tf
src/aks/bpd_secrets.tf
src/aks/locals.tf
src/aks/rtd_secrets.tf
src/aks/secrets.tf
src/env/dev/backend.ini
src/monitor.tf
src/outputs.tf
src/terraform.sh

- add APPLICATIONINSIGHTS_CONNECTION_STRING as secret
- add subscription switch into terraform.sh
log management to application insights
---

[CEN-362] Add APPLICATIONINSIGHTS_CONNECTION_STRING

---

src/aks/bpd_secrets.tf
src/aks/rtd_secrets.tf
src/aks/subscriptions/DEV-CSTAR/terraform.tfvars
src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
src/aks/subscriptions/UAT-CSTAR/terraform.tfvars

[CEN-362] App insights conf

---

src/aks/subscriptions/DEV-CSTAR/terraform.tfvars
src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
src/aks/subscriptions/UAT-CSTAR/terraform.tfvars

change applicationinsights-agent.jar filename
remove version to decuple systems
---

Change applicationinsights-agent.jar filename

---

src/api.tf

Add instrumentation key to APIM

---

src/database.tf

Add database creation via tf

---

src/.terraform.lock.hcl
src/aks.tf
src/api.tf
src/env/dev/terraform.tfvars
src/main.tf
src/security.tf
src/terraform.sh
src/variables.tf

AKS AD Admin Group ID

---

src/terraform.sh

Add output support

---

src/aks/rtd_secrets.tf
src/aks/terraform.sh

Change rtd schema name

---

src/aks/scripts/setup.sh

Add AAD auth

---

src/aks/serviceaccounts.tf

Move azure_devops sa to kube-system namespace

---

src/aks/locals.tf
src/aks/secrets.tf
src/aks/serviceaccounts.tf

insert into keayvault azure devops service account secret
---

Save sa azdo keyvault

---

src/README.md
src/modules/app_gw/README.md
src/modules/app_gw/main.tf
src/modules/app_gw/outputs.tf
src/modules/app_gw/variables.tf
src/network.tf
src/security.tf
src/variables.tf

This PR proposes to introduce a new module for a Muti-listener app gateway with a simplified interface to configure listeners and their route to backend.
- New module to support a multi listener app gateway
- Self Signed Certificates tu enable HTTPS
- Data object to access certificate data stored in the key vault
- New module instance
This PR solves the problem of supporting a multilistener gateway
The module can't manage the creation of a listener specific ssl profile
---

[CEN-166] Add Multilistener Gateway

---

src/network.tf

App Gw Remove version in secret id

---

src/aks/.terraform.lock.hcl
src/aks/main.tf
src/aks/rbac.tf
src/aks/serviceaccounts.tf
src/aks/subscriptions/DEV-CSTAR/terraform.tfvars
src/aks/variables.tf

Add rbac reader

---

src/.terraform.lock.hcl
src/aks/.terraform.lock.hcl
src/aks/rtd_secrets.tf
src/aks/secrets.tf
src/psql/.terraform.lock.hcl
src/psql/subscriptions/DEV-CSTAR/terraform.tfvars

Add rtd user grants

---

src/README.md
src/network.tf

Route table peering sia

---

src/api.tf
src/outputs.tf

Use custom domain apim

---

src/network.tf

Fix route table uat apim record

---

src/api.tf
src/env/dev/terraform.tfvars
src/network.tf
src/security.tf

Fixed reference to bpd_api_product policy file
---

Fix bpd api product policy

---

src/api.tf
src/api_product/app_io/policy.xml.tmpl

Set url direct to backend

---

src/api/bpd_hb_citizen/v2/patch_update_payment_method.xml

Resolved cast exception on policy application (bug on prod environment, fixed in UAT)
---

fixed fix-bpd_hb_citizen v2 patch_update_payment_method policy

---

src/api.tf

fixed subscription_required on API
---

fixed subscription_required on API

---

src/README.md
src/dns.tf
src/outputs.tf

Dns records

---

src/api.tf
src/api/bpd_hb_payment_instruments/original/5f98984972e5123d4571984b_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/5faade7fc12a87300a91769a_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/5fabb9644b1afaae5cc91a19_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/5fdb377a52411ce8e7b9d5f6_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/5fdb37ee7e211f8e0ac2dc45_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/6040bbd70a02ff56cad6aefd_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/deletepaymentinstrumenthb_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/enrollPaymentInstrumentHB_policy.xml.tpl
src/api/bpd_hb_payment_instruments/original/statuspaymentinstrumenthb_policy.xml.tpl
src/api/pm_admin_panel/walletv2_policy.xml.tpl
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/outputs.tf
src/variables.tf

Change pm backend host to url
Fix with url for DEV environment
---

Refactor pm backend host to url

---

src/README.md
src/api.tf
src/env/dev/terraform.tfvars
src/security.tf
src/variables.tf

Keyvault devops policy

---

src/psql/subscriptions/DEV-CSTAR/terraform.tfvars

Add grant sequence to bpd user

---

src/env/dev/terraform.tfvars

Updated PM mocked services
---

mock PM service updated

---

.gitignore
.pre-commit-config.yaml
src/README.md
src/database.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/monitor.tf
src/outputs.tf
src/variables.tf

Add postgresql alerts

---

src/database.tf
src/env/dev/terraform.tfvars
src/monitor.tf
src/security.tf

Change notification groups

---

src/README.md
src/aks.tf
src/database.tf
src/env/dev/terraform.tfvars
src/monitor.tf
src/terraform.sh
src/variables.tf

AKS alerts

---

src/aks.tf
src/env/dev/terraform.tfvars
src/messages.tf
src/variables.tf

EventHub Alerts

---

src/api.tf

Apim integration with appinsight

---

src/network.tf

Route table association

---

src/README.md
src/env/prod/terraform.tfvars
src/network.tf
src/redis_cache.tf
src/variables.tf

Redis subnet prod integration

---

src/aks.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/messages.tf
src/variables.tf

Uat prod alerts

---

src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars

Fix key permission eventhub

---

src/api.tf

Product approval_required true

---

src/README.md
src/api.tf

Rename api 

---

src/api.tf

Restored product approval_required = false

---

src/.terraform.lock.hcl
src/README.md
src/api.tf
src/main.tf
src/redis_cache.tf

Add external redis to APIM
Docs changes @uolter @pasqualedevita please update your terraform docs binary version
---

Add external redis to APIM

---

src/.terraform.lock.hcl
src/README.md
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/network.tf
src/storage.tf
src/variables.tf

VPN Gateway

---

src/README.md
src/database.tf

Allow access to azure services psql

---

src/README.md
src/database.tf

Update Postgresql module version
Fix failure due to storage_mb changed outside terraform with autogrow
---

Update psql module

---

src/README.md
src/storage.tf

Missing \ and docs

---

src/dns.tf
src/dnsforwarder.tf
src/terraform.sh

Fix corefile dns storage uplouad

---

src/aks/subscriptions/DEV-CSTAR/terraform.tfvars
src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
src/aks/subscriptions/UAT-CSTAR/terraform.tfvars

awardwinner configmap new entry
---

awardwinner configmap new entry

---

src/messages.tf

Event hub multiple network links

---

src/database.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/variables.tf

Add postgres tuning conf

---

src/aks/subscriptions/DEV-CSTAR/terraform.tfvars
src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
src/aks/subscriptions/UAT-CSTAR/terraform.tfvars

Consap SFTP file sent through public ips
---

consap public ips

---

src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars

PM backend url resolved

---

src/env/uat/terraform.tfvars

Change sku apim uat

---

src/network.tf

Add routing table to PM

---

src/network.tf

Change peering routing

---

migration-scripts/db/01-create_database.sh
src/env/dev/terraform.tfvars

Add vpn dev env

---

migration-scripts/db/.env.sample
migration-scripts/db/02-prepare_destination_server.sh
migration-scripts/db/05-post_restore_cstar.sh
src/database.tf
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars

fix variables

---

src/api.tf
src/api/rtd_payment_instrument_manager/get-hash-salt_policy.xml.tpl
src/security.tf

Apim fix api certificate thumbprint

---

src/.terraform.lock.hcl
src/aks/.terraform.lock.hcl
src/aks/main.tf
src/aks/serviceaccounts.tf
src/jumphost.tf
src/main.tf
src/messages.tf
src/monitor.tf
src/storage.tf
src/terraform.sh

Upgrade providers, fix tfsec ignore

---

src/api.tf

Set apim products approval required true

---

src/api.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/monitor.tf
src/security.tf
src/variables.tf

Fix azurerm monitor action group use common alert schema

---

migration-scripts/db/05-post_restore_cstar.sh

Fix post restore

---

src/api.tf
src/api/pm_admin_panel/walletv2_policy.xml.tpl
src/security.tf

Remove basic auth password from template

---

src/api.tf

Fix service url pm_admin_panel api

---

src/README.md
src/api.tf

Product subscriptions limit required

---

src/network.tf

Applied in UAT only ... so far.
---

Removed routes pm sia.

---

src/psql/migrations/UAT-CSTAR/bpd/V17__bpd.grant_ monitor_bpd_award_period.sql

Migration script to set missed grant for user monitor

---

src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars

Disable db replica uat and dev

---

src/env/prod/terraform.tfvars
src/network.tf

Fix management dns record for prod

---

src/api/bpd_hb_payment_instruments/original/getstatuspaymentinstrumenthb_policy.xml.tpl
src/api/bpd_hb_payment_instruments/v2/getstatuspaymentinstrumenthb_policy.xml.tpl

Update api policy payment instrument

---

src/aks/bpd_secrets.tf
src/aks/locals.tf

Fix confg map db dev uat

---

src/README.md
src/aks.tf
src/database.tf
src/env/uat/terraform.tfvars
src/messages.tf
src/variables.tf

Disable UAT alerts

---

src/README.md
src/api.tf
src/env/dev/terraform.tfvars
src/network.tf
src/security.tf
src/variables.tf

App gw to apim api https

---

src/README.md
src/env/dev/terraform.tfvars
src/network.tf
src/variables.tf

Also refer to this confluence page: https://pagopa.atlassian.net/wiki/spaces/CEN/pages/286558334/Certificati+client
---

Client cert app gw

---

src/env/dev/terraform.tfvars
src/network.tf

Dev config refactoring

---

src/aks/locals.tf

Do not connect to db replica

---

src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars

add rtd-log to event-hub
csv connection need to send log to event-hub
---

Add rtd log

---

src/api/bpd_hb_payment_instruments/original/getstatuspaymentinstrumenthb_policy.xml.tpl

Change policy get-instrument status

---

src/database.tf
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/variables.tf

- add PDND whitelist ip
- requires public access
PDND need to access to postgresql
---

[#CEN-513] Add PDND whitelist ip

---

src/aks/subscriptions/UAT-CSTAR/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/network.tf
src/variables.tf

scale up application gateway
---

Scale up envs

---

src/aks/locals.tf
src/aks/subscriptions/PROD-CSTAR/terraform.tfvars
src/aks/variables.tf

add new variable enable_postgres_replica
enable connection to postgres replica with vaiable
---

Add aks variable postgres replica connection

---

src/api/bpd_hb_payment_instruments/original/openapi.json.tpl

Change openapi definition getstatuspaymentinstrumenth

---

src/network.tf

New entry route table haproxy

---

src/api/bpd_hb_payment_instruments/v2/deldeletepaymentinstrumenthb_policy.xml.tpl

HB Payment Instrument deletePaymentInstrument V2 aligned to PROD
---

HB Payment Instrument deletePaymentInstrument V2 aligned to PROD

---

src/README.md
src/api.tf
src/api/monitor/mock_policy.xml
src/api/monitor/openapi.json.tpl

Monitor api

---

src/README.md
src/database.tf

Remove tags alerts db

---

src/api.tf

Fix api blobstorage

---

src/api.tf

Temporary host for the get-hashed-pans api in production only

---

src/security.tf

Add key vault policy fo developers

---

src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/security.tf
src/variables.tf

add key vault policy for 
- security ad group
- azure devops TLS cert service principal
---

add keyvault policy

---

src/default.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/security.tf

Since the number of PODS in k8s cluster has been reduced as follow
and now the number of connection is lower,
this PR proposes to scale down the DBMS to 16 cpu. 
- Modified DBMS sku in TF vars for the production stage
This change is a way to reduce the cost of the system as a consequence of the load reduction. 
---

[CEN-642] Scale Down the DBMS

---

src/README.md
src/aks.tf
src/messages.tf

Remove alerts tags

---

src/README.md
src/main.tf
src/modules/app_gw/README.md
src/modules/app_gw/main.tf
src/modules/app_gw/outputs.tf
src/modules/app_gw/variables.tf
src/monitor.tf
src/network.tf
src/outputs.tf
src/security.tf

enable diagnostic settings for the pp gw

---

src/k8s/rbac.tf

add edit_extra role and bindings for ad groups with edit permissions (internal developers)
this privileges are required to run terraform plan/apply 
---

Add extra permission on k8s for devs

---

src/README.md
src/modules/app_gw/main.tf
src/modules/app_gw/variables.tf
src/network.tf
src/security.tf

forward the app gw logs to the security storage account

---

.devops/deploy-pipelines.yml

pr trigger definition

---

.devops/deploy-pipelines.yml
src/.terraform.lock.hcl
src/env/dev/backend.ini
src/env/dev/terraform.tfvars
src/env/prod/backend.ini
src/env/prod/terraform.tfvars
src/env/uat/backend.ini
src/env/uat/terraform.tfvars
src/security.tf
src/terraform.sh
src/variables.tf

Release dev

---

src/modules/app_gw/main.tf
src/network.tf
src/security.tf

Renaming devops service principal

---

src/README.md
src/modules/app_gw/README.md
src/modules/app_gw/main.tf
src/network.tf

Fix hidden changes in app gw

---

src/README.md
src/aks.tf
src/modules/app_gw/README.md
src/modules/app_gw/main.tf
src/network.tf

add aks node pool max-surge to 33%
https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#customize-node-surge-upgrade
---

INFRA-216 set max surge

---

src/aks.tf

INFRA-216 set max surge (#190)

---

src/README.md
src/aks.tf
src/modules/app_gw/README.md
src/modules/app_gw/main.tf
src/network.tf

INFRA-216 set max surge PROD

---

src/README.md
src/env/uat/terraform.tfvars

Scale down app gw uat

---

src/env/dev/terraform.tfvars
src/security.tf

1. fix devops_service_connection_object_id for dev env
2. grant to devs permissions to plan/apply in uat/prod
---

CEN-741 Permission to plan/apply for devs

---

src/README.md
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/k8s/fa_configmaps.tf
src/k8s/fa_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/k8s/variables.tf
src/modules/app_gw/README.md
src/modules/app_gw/main.tf
src/network.tf
src/security.tf

Release prod

---

src/k8s/fa_configmaps.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/k8s/variables.tf

This PR proposes to add a basic configmap, to be improved when requirements will be clear enough, for microservice Transaction
- A new configmap for microservice Transaction
The configmap in needed to deploy the microservice
---

[CEN-745] Config Map for FA ms Transaction

---

src/k8s/fa_ingress.tf

This PR proposes to add an Ingress for FA namespace
- A new Ingress resource in `fa` namespace
Route requests to services used to expose microservices
---

[CEN-748] FA Ingress

---

src/env/uat/terraform.tfvars
src/variables.tf

Scale to zero dev/uat app gateway
cost savings
---

Scale to zero dev/uat app gateway

---

src/env/uat/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars

scale down ingress and aks node pool
cost savings
---

Scale down aks UAT

---

src/env/uat/terraform.tfvars

scale down postgresql uat from `GP_Gen5_8` to `GP_Gen5_4`
cost saving
---

Scale down postgresql UAT

---

src/api.tf
src/network.tf

change keyvault certificate URI
apim custom domains requires to ref keyvault certificate without final `/`
---

[CEN-768] Fix apim custom domain certificate

---

src/aks.tf

add dev adgroup as admin in dev env
devos bottlenack
---

Add aks admins dev env

---

src/api.tf

Send apim diagnostic settings to prod-sec workspace

---

src/env/prod/terraform.tfvars

scale in appgateway min instances to 2
fine tuning and cost saving
---

[CEN-767] Scale in app gateway prod

---

src/api.tf
src/dns_public.tf
src/network.tf

update management.cstar.pagopa.it dns record
This PR is already manually applied because we need to align terraform state without delete DNS records
fix dns A record
---

CEN-797] Align management dns record

---

src/k8s/bpd_configmaps.tf

- Add env var to FA's ingress transaction microservice
This change is mandatory to invoke the APIs exposed by  FaTransaction from BPD Mock
---

Add host name whit ingress reference

---

src/k8s/configmaps/famsnotificationmanager/NOTIFICATION_SERVICE_INVOICE_MARKDOWN_KO.txt
src/k8s/configmaps/famsnotificationmanager/NOTIFICATION_SERVICE_INVOICE_MARKDOWN_OK.txt
src/k8s/fa_configmaps.tf
src/k8s/fa_ingress.tf
src/k8s/fa_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/k8s/variables.tf

- Add configmap basic configmap for FaMsNotificationManager microservice
- Add secret for FaMsNotificationManager microservice
- Add env var for markdown's push notification
This change is mandatory to deploy NotificationManager microservice and create push notification's message
---

CEN-950 configmap and secret for FaNotificationManager microservice

---

src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars

This PR proposes to add a Horizontal POD Autoscaler resource to microservice Enrollment.
- New HPA for ms enrollment
---

[CEN-911] Add HPA to microservice Enrollment

---

src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars

This PR proposes to add a HPA resource to autoscale micro-service winning transaction
- New HPA for micro-service winning transaction
This change is required to autoscale micro-service winning transaction
---

[CEN-912] Horizontal POD Autoscaler micro-service BPD Winning Transaction

---

src/k8s/fa_configmaps.tf
src/k8s/fa_secrets.tf

- Add secret for fa-trx-error pointing
- Add configmap for fa-trx-error pointing
Those changes are mandatory to write items in fa-trx-error's topic
---

add configmap and secret for fa-trx-error

---

src/api.tf
src/api/fa_ext_merchant/onboardingMerchantByOtherUsingPut_policy.xml.tpl
src/api/fa_ext_merchant/onboardingMerchantByProviderUsingPut_policy.xml.tpl
src/api/fa_ext_merchant/swagger.json.tpl
src/api/fa_io_merchant/onboardingMerchantByIOUsingPut_policy.xml.tpl
src/api/fa_io_merchant/swagger.json.tpl
src/api/fa_io_transaction/openapi.json.tpl
src/api/fa_mock/sendAcquirerTransactionUsingPOST_policy.xml.tpl
src/api/fa_mock/sendRegisterTransactionUsingPOST_policy.xml.tpl
src/api/fa_mock/swagger.json.tpl

- Add mock's APIs
- Add merchant's APIs for IO and External invocation
This changes are mandatory to invoke service required by POC (mock) and onboarding new merchant
---

add APIs for mock and merchant service

---

src/api.tf
src/monitor.tf
src/security.tf

fix unwanted changes logs to prod sec
---

fix unwanted changes logs to prod sec

---

src/env/uat/terraform.tfvars

This PR propose to scale down UAT DBMS to `Gen5 2 vcore`.
- Scale down DBMS SKU
- Set alarm threshold accordingly
This change are required to reduce system costs
---

[CEN-1053] Scale Down UAT DBMS

---

src/api/fa_io_transaction/getTransactionListUsingGET_policy.xml.tpl

- Fix rewrite-uri of policy Fa Transaction IO list
This change is mandatory to invoke API
---

fix policy of transaction io list API

---

src/env/prod/terraform.tfvars

This PR proposes to remove production replica of the DBMS and related alarms and configurations
- Set `enable_replica` flag to `false` in `postgres` module
- Remove configuration to whitelist PDND data lake on replica
- Remove alarm on replica lag
As the DBMS mainly support cashback, and the program is canceled, we want to reduce infrastructure cost to its minimum
---

[CEN-1092] Remove DBMS replica and related configurations and alarms

---

src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars

This PR proposes to increase the scheduling of the extraction of payment instruments to every 15 minutes, in the DEV environment. This is useful in order to quickly iterate during internal testing.
Set custom schedule crontab (every 15 minutes) on DEV via configmap
This change is needed in order to have a fresh payment instruments list in DEV after changes applied to DB.
---

[CEN-1096] extract payment instruments every 15 minutes in DEV

---

src/k8s/rtd_configmaps.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars

This PR updates the default configmap for the batch acquirer (rtdtransactionfilter) service in DEV environment with new (and more sane) configuration values.
Updated rtdtransactionfilter deployment configmap
The old configuration was stale after a period of development
---

[CEN-1126] Updated batch acquirer DEV (and default) configmap

---

src/api.tf
src/env/prod/terraform.tfvars
src/k8s/rtd_configmaps.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/outputs.tf
src/psql/migrations/PROD-CSTAR/bpd/V10__optimization_delete_citizen.sql
src/redis_cache.tf

Scale in min capacity to 1
cost savings
---

Scale in appgateway

---

src/aks.tf

Aks audit log

---

src/api.tf
src/api/fa_ext_merchant/activeContractByShopIdUsingGet_policy.xml.tpl
src/api/fa_ext_merchant/contractListByShopIdUsingGet_policy.xml.tpl
src/api/fa_ext_merchant/swagger.json.tpl

- Add endpoints in FaExtMerchant API
This change is mandatory to invoke new APIs exposed by FaMsMerchant to get provider's list in contracts linked to a shopId
---

[CEN-1132] Get provider's info by shop id

---

src/api.tf
src/api/fa_ext_provider/providerListUsingGET_policy.xml.tpl
src/api/fa_ext_provider/swagger.json.tpl

- Add new API to get provider's list
This change is necessary to get list of providers onboarded in FA
---

Cen 1203 get provider list

---

src/.terraform.lock.hcl
src/README.md
src/api.tf
src/env/prod/terraform.tfvars
src/k8s/bpd_configmaps.tf
src/k8s/bpd_deployments_hpa.tf
src/k8s/bpd_secrets.tf
src/k8s/fa_configmaps.tf
src/k8s/fa_secrets.tf
src/k8s/rtd_configmaps.tf
src/k8s/rtd_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/k8s/variables.tf
src/main.tf
src/monitor.tf

Web availability tests

---

src/k8s/main.tf
src/k8s/rtd_configmaps.tf
src/k8s/subscriptions/DEV-CSTAR/backend.ini
src/k8s/subscriptions/PROD-CSTAR/backend.ini
src/k8s/subscriptions/UAT-CSTAR/backend.ini

migrate aks terraform state file into main terraform storage account
security improvements
old terraform state is locked to prevent changes until this pr is merged
---

[#CEN-1174] Migrate k8s state to main storage account

---

src/storage.tf

remove migrated aks storage account https://github.com/pagopa/cstar-infrastructure/pull/304
infra/security debt
---

CEN-1238 Remove aks terraform storage

---

src/api.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/network.tf
src/variables.tf

- migrate to new app gateway module 2.0.23
- set only TLS 1.2 cipher_suites
- add alerts
- disable waf for dev/uat envs
security/infra technical debt
---

CEN-1178 App gateway improvements

---

.github/workflows/static_analysis.yml
.pre-commit-config.yaml
src/env/dev/terraform.tfvars
src/k8s/main.tf
src/k8s/subscriptions/DEV-CSTAR/backend.ini
src/k8s/subscriptions/PROD-CSTAR/backend.ini
src/k8s/subscriptions/UAT-CSTAR/backend.ini
src/k8s/terraform.sh
src/psql/main.tf
src/psql/subscriptions/DEV-CSTAR/backend.ini
src/psql/subscriptions/PROD-CSTAR/backend.ini
src/psql/subscriptions/UAT-CSTAR/backend.ini
src/psql/terraform.sh

- terraform static analysis to code reviews
Improve quality with automatic test automation
---

Add terraform static analysis to code reviews

---

src/k8s/fa_configmaps.tf

- Modify env var to invoke correct AdE's endpoint
This change i required to invoke the correct endpoint exposed by AdE
---

fix env var

---

src/env/uat/terraform.tfvars

- Enable flexible server flag in uat config file
This change is required to enable flexible server in uat env
---

[CEN-1322] enable flexible in uat env

---

src/api.tf
src/api/fa_io_transaction/openapi.json.tpl
src/api/fa_register_transaction/openapi.json.tpl
src/env/dev/terraform.tfvars
src/env/uat/terraform.tfvars
src/variables.tf

- Add env variable to keep status of enabling API for FA
- Modify old count value from string to bool depending of the deploy env
This change is required to expose API for FA in UAT environment
---

[CEN-1309] expose API of FA also in UAT env

---

src/api/fa_hb_customer/deleteUsingDELETE_policy.xml.tpl
src/api/fa_io_customer/deleteUsingDELETE_policy.xml.tpl

- Fix rewrite-url
- Modify channel from path variable to query param
---

[CEN-1349] fix api redirect and modify path variable to path parameter for channel value

---

src/api.tf
src/api/azureblob/azureblob_policy.xml
src/dns_private.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/network.tf
src/storage.tf
src/variables.tf

This PR proposes to add a private endpoint to access CSTAR blob storage. This is required to switch-off public access and increase security.
- A new private dns zone for storage accounts
- A new subnet and private endpoint for cstar-blob-storage
- Disable public access on cstar-blob-storage
- Grant "Data Contributor Role" to APIM
- Modify auth-mode permission on a test container
- Modify a cstar-blob-storage test api to use the private endpoint. The change, after tests, must be extended to all apis which use the blob storage
The blob storage will host files coming from acquirers, so its security must be improved
---
The PR can't be applied without higher privileges, since Terraform doesn't have the permission to alter APIM permission on Blob Storage.
Moreover, network rules (e.g. …

CEN-1350 Blob storage private endpoint

---

src/api.tf
src/api/fa_register_transaction/getPosTransactionCustomerUsingGET_policy.xml.tpl
src/api/fa_register_transaction/getPosTransactionUsingGET_policy.xml.tpl
src/api/fa_register_transaction/openapi.json.tpl

- Add authCode in request body on POST call
- Fix endpoint signature in POST (removed unused pathVariable)
- Add GET in swagger
Those changes are required to permit the invocation by POS to create Invoice Request and GET Invoice Status
---

[CEN-1367] add authCode in pos POST call and create GET structure

---

src/k8s/fa_configmaps.tf

- Add config for customer data host in DEV and UAT env
This change is required in order to split calls between ADE and Customer Data (on mock) to get information about invoices
---

[CEN-1370] create config for customer data

---

src/k8s/rtd_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars

This PR proposes to add a secret for ms rtd-decrypter
- new secret
- access platform event hub
---

[CEN-1361] Add rtd ms decrypter secret to access platform event hub

---

src/api.tf
src/env/dev/terraform.tfvars
src/env/uat/terraform.tfvars
src/variables.tf

This PR enables the diagnostic logs via application insights for the API RTD CSV Transaction.
- Bump 'apim' module to last available version v2.2.1
- new 'azurerm_api_management_api_diagnostic'
- minor refactoring of rtd_csv_* modules toggle strategy (feature flag vs env)
To allow tracking the Batch Acquirer version in use from the Acquirers we need to collect the 'User-Agent' header on some API that is called on each execution. The API RTD CSV Transaction is ideal because satisfies this constraint and also has a very low TPS (a few hundred per day top).
---

[CEN-1408] Enable diagnostics on API RTD CSV Transaction

---

src/api/fa_ext_merchant/swagger.json.tpl
src/api/fa_io_merchant/swagger.json.tpl
src/api/fa_io_transaction/openapi.json.tpl
src/api/fa_mock/swagger.json.tpl
src/api/fa_register_transaction/openapi.json.tpl

- Add examples whit values
- Reformat api's structure
---

Cen 1414 refactoring examples api fa

---

src/api.tf

This PR proposes to remove Issuer API from APIM due to the end of the cashback program.
- Remove all HB api.
Support end of life of cashback program.
---

[CEN-1389] Remove Issuer Api

---

src/k8s/rtd_secrets.tf

[CEN-1445] Make secret optional

---

src/env/prod/terraform.tfvars
src/k8s/rtd_configmaps.tf
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/security.tf

This PR promotes in PROD the APIs needed in order to ship the release 1.1.0 of the Batch Acquirer service.
- enabled RTD internal storage API via feature flag on PROD
- enabled RTD CSV Transaction API via feature flag on PROD
- enabled Event Grid integration via feature flag on PROD
- updated remote URI on pre-commit-hook from git:// (deprecated) to https://
- promotion of the service from UAT to PROD
---

[CEN-1457] Enable new RTD APIs and EventGrid integration on PROD

---

src/api_cdc.tf
src/api_product/cdc_api/policy.xml
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/variables.tf

This PR proposes to add an APIM product for "Carta della Cultura".
- New APIM Product
- New Feature Flag to enable the product in different staging environment
This change is required to collect in the same product all the APIs and operations needed for the project "Carta della Cultura"
---

[CDC-24] Add CDC Product and feature flag

---

src/k8s/rtd_configmaps.tf
src/k8s/rtd_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/k8s/variables.tf

This PR proposes to add secrets and a configmap to configure ingestor microservice.
- New secret containing connection strings to event hub
- New configmap containing uri of blob storage HTTP interface
This PR is required to allow ms ingestor startup.
---

Cen 1445 create rtd secret to produce on rtd trx ehub

---

src/api/cdc/openapi.sogei.yml.tpl
src/api_cdc.tf
src/api_product/cdc_api/policy.xml

This PR proposes to expose SOGEI endpoint to health check CDC API.
-  New API in CDC product needed to expose SOGEI health-check endpoint
- Test Availability of SOGEI services
---

[CDC-25] Expose health-check sogei

---

src/database.tf
src/dns_private.tf
src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars
src/network.tf
src/variables.tf

This PR proposes to add a Cosmos/Mongo account + a transaction DB to support ingestion pipeline of TAE application
- New Cosmos/Mongo account
- New Transaction DB
- New dedicated subnet
- New private dns zone to resolve private endpoint
This PR is required to have a scratch db where transactions can be ingested before aggregation for ADE
---

[CEN-1282] Add cosmos db (mongo) with a transaction database

---

src/network.tf

addrouting to nexi or dev uat
---

Add routing to nexi vnet hub for dev uat

---

src/README.md
src/dns_private.tf
src/env/dev/terraform.tfvars
src/env/uat/terraform.tfvars
src/variables.tf

Add DNS record for tkm storage account:
- DEV -> u89blobtestaccount.blob.core.windows.net
- UAT -> tkmstorageblobuatpci.blob.core.windows.net
---

Add dns fot tkm storage

---

src/security.tf

azure devops minor fix

---

src/domains/idpay-common/03_database.tf
src/domains/idpay-common/README.md

add key vault entry for idpay mongodb
need to use the mongodb connection string for deployment configuration
---

[IID-14] Add key vault entry for idpay mongodb connection string

---

src/README.md
src/domains/idpay-app/00_network.tf
src/domains/idpay-app/04_apim_api_devops.tf
src/domains/idpay-app/99_locals.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/base_policy.xml
src/network_aks_domains.tf

- added vnet integration peerings 2 aks vnet
Allow APIM to comunicate with AKS platform
---

fix: Vnet integration peering created

---

src/README.md
src/datafactory.tf

This PR proposes to add an ADF Linked Service for Cosmos/Mongo DB
- New ADF Linked Service for ADF Mongo DB
This PR allows ADF pipelines to access data in Cosmos/Mongo DB
---

[TAE-54] Add ADF Linked Service for Cosmos/Mongo DB

---

src/README.md
src/tae_pipeline.tf

This PR proposes to add a trigger for Aggregate Ingestor pipeline
- New Blob storage Trigger
This trigger starts the Aggregate Ingestor pipeline
---

[TAE-55] Add pipeline trigger

---

src/README.md
src/database.tf
src/tae_database.tf
src/tae_datasets.tf
src/tae_pipeline.tf

This PR proposes to create two datasets to be used in ADF pipelines.
- Refactor TAE DB: a new db is created (which replaces the old one) containing a new collection
- AcquirerAggregate Dataset, pointing to files uploaded by acquirers on blob storage
- Aggregate Dataset, pointing records stored in mongoDB
This PR defines datasets to be used in pipeline which ingests decrypted acquirer files
---

[TAE-56] Create datasets

---

src/domains/idpay-common/04_eventhub.tf
src/domains/idpay-common/README.md

event hub module fixed to v2.18.6
---

pre-commit fix

---

src/sftp.tf

This PR proposes to add a prefix filter to SFTP subscription in order to obtain only events of interest.
- add prefix filter to SFTP subscription.
This changes allowed us to filter only interesting events, reducing noise for system monitoring.
---

[RTD-219] Filter files created in ade container for sftp subscription

---

src/pipelines/aggregatesIngestor.json

This PR proposes to fix date format in output file to comply with interface agreement
- Fix pipeline json by setting date format
This PR is needed to made output format compliant with interface agreement
---

[TAE-11] Fix date formats

---

src/env/dev/terraform.tfvars
src/env/prod/terraform.tfvars
src/env/uat/terraform.tfvars

add consumer group for consume data from rtd-trx topic (the required connection string will be copied into idpay keyvault with a separate PR)
need to consume rtd-trx event 
---

add idpay consumer group for rtd-trx

---

src/README.md
src/tae_datasets.tf

This PR proposes to add a new dataset to represent ack files from ADE.
- New Data Factory dataset
The proposed dataset will be used as source in the AckIngestor pipeline
---

[TAE-73] Add adeack dataset

---

src/README.md
src/sftp.tf

This PR proposes to create many directories in root dir of SFTP server
- new in directory
- new out directory
- new error directory
- new ack directory
This PR is motivated by the interface agreement with ADE, which requires different directory for different use cases
---

[TAE-74] Create virtual directories

---

src/tae_datasets.tf

This PR proposes to modify Destination Aggregate dataset to write in IN directory of ADE container hosted on SFTP server.
- Modify dataset location setting folderName
This change is required to comply with interface agreement
---

[TAE-75] Modify Destination Aggregate to write in IN directory of ADE container

---

src/api/fa_register_transaction/getPosTransactionCustomerUsingGET_policy.xml.tpl
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars

- use fake notification endpoint for FA
- removed apim policy which mock "mario rossi" as customer for `transaction/pos/invoice/request/{{invoice_id}}/customer`
---

Fix API Manager and Notification

---

src/api/cdc/policy.jwt.xml.tpl

- removed two headers forwared by apim to sogei: `X-Forwarded-For` e `x-bpd-token`
---

Removed headers APIM -> CDC 

---

src/domains/idpay-app/.terraform.lock.hcl
src/domains/idpay-common/04_eventhub.tf
src/domains/idpay-common/99_variables.tf
src/domains/idpay-common/README.md
src/domains/idpay-common/env/dev/terraform.tfvars

add eventhub for idpay rule-engine 
IdPay rule engine services mustbe async, therefore the queue communication mode was chosen
This PR could have merge conflict with 
- ISB-214-creazione-coda-timeline
- ISB-213-creazione-code-check-iban
because of changes in the same eventhub section
---

IREER-90 - add eventhub for rule-engine services

---

src/domains/idpay-common/04_eventhub.tf
src/domains/idpay-common/README.md
src/domains/idpay-common/env/dev/terraform.tfvars

- add topic for check iban business case
- add jaas_config string on idpay keyvault
create async communication with check iban services
---

add idpay-checkiban topic

---

src/README.md
src/api_rtd.tf
src/datafactory.tf
src/env/uat/terraform.tfvars
src/k8s/rtd_configmaps.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/tae_pipeline.tf

This PR proposes to promote to UAT TAE datafactory
- enable flags
- add Data Contributor rolw
Test Acquirer integraiton in UAT
---

[TAE-81] Promote TAE datafactory to UAT

---

src/domains/idpay-app/.terraform.lock.hcl
src/domains/idpay-common/.terraform.lock.hcl
src/domains/idpay-common/00_network.tf
src/domains/idpay-common/05_redis_cache.tf
src/domains/idpay-common/99_variables.tf
src/domains/idpay-common/README.md
src/domains/idpay-common/env/dev/terraform.tfvars
src/env/dev/terraform.tfvars
src/k8s/scripts/setup.sh

add redis cache to idpay project common
add a new snet (/24) only when Premium sku is defined
add cache for idpay project
---

IREER-92-creazione-cache

---

src/env/dev/terraform.tfvars
src/k8s/rtd_secrets.tf

This PR fix topic name and consumer group name for enrolled-payment-instrument microservice
---

[RTD-295] Fix typo enrolled queue

---

src/env/uat/terraform.tfvars

Add an IP to SFTP whitelist
---

[TAE-91] Modify SFTP whitelist

---

src/99_outputs.tf
src/README.md
src/storage.tf

Storage account apim backups

---

.devops/backupa-apim-deploy-pipelines.yml

Apim backup pipeline

---

src/domains/idpay-app/04_apim_api_token_exchange.tf
src/domains/idpay-app/api/idpay_token_exchange/jwt_exchange.xml.tpl

- Modify token echange api from GET to POST anche add /token to path
- Update policy in order to validate token from header and return a new idpay token as response 
Change token exchange policy to be compliant with security guidelines
---

IPE-239 update api and policy for token echange

---

src/env/uat/terraform.tfvars

[TAE-71] Fix allowed IPs on SFTP

---

src/api/rtd_sender_api_key_check/openapi.yml
src/api/rtd_sender_mauth_check/openapi.yml

This PR proposes to add a feedback other than status code 200 for integration check calls.
- add "PASS" as response body.
This change allows the sender to avoid confusing scraping-protection with correct results.
Targets:
- module.rtd_sender_mauth_check[0].azurerm_api_management_api.this
- module.rtd_sender_api_key_check[0].azurerm_api_management_api.this
---

[RTD-373] Add test result as response body

---

src/domains/tae-common/02_blob_storage.tf

[TAE-144] Align storage accounts

---

src/README.md
src/rtd_database.tf

- add file register collection to rtd cosmos DB
This PR creates a dedicated collection for file register micro service.
The collection was already present, created by the file register microservice.
Target:
- azurerm_cosmosdb_mongo_collection.file_register[0]
---

[RTD-268] Add file register collection

---

src/aks-platform/00_azuread.tf
src/aks-platform/04_rbac.tf
src/aks-platform/README.md

add RBAC for developers
developers adgroup access to cluster
---

Add RBAC for developers

---

src/domains/tae-app/07_datasets.tf
src/domains/tae-app/08_pipeline.tf
src/domains/tae-app/pipelines/ackIngestor.json

During the mapping of the return pipeline via Terraform code, transcription errors were made which led to inconsistencies during the apply.
- align the code to the ADF studio editor.
This PR alignes the terraformed pipeline to the one modified by web interface.
Domain: tae-app
---

[TAE-147] Fix pipeline code

---

.devops/rtd-code-review-pipelines.yml
.devops/rtd-deploy-pipelines.yml
src/domains/rtd-app/03_serviceaccounts_azure_devops.tf
src/domains/rtd-app/README.md
src/domains/rtd-common/01_keyvault_0.tf
src/domains/rtd-common/README.md

- added rtd pipelines
- added kubernetes configuration
Allow rtd to run pipelines
---

feat: Rtd-support-pipelines

---

src/core/env/prod/terraform.tfvars

This PR proposes to whitelist Client IP on SFTP interface
---

[TAE-171] Whitelist IP

---

src/domains/tae-common/02_blob_storage.tf
src/domains/tae-common/99_variables.tf
src/domains/tae-common/README.md
src/domains/tae-common/env/dev/terraform.tfvars
src/domains/tae-common/env/uat/terraform.tfvars

This PR aims to connects TAE storages (blobstorage and sftp) to analytics workspace.
- linked blobstorage to analytics workspace
- linked sftp blobstorage to analytics workspace
---

[TAE-167] Storage accounts observability

---

src/core/env/prod/terraform.tfvars
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars

This PR proposes to add an HPA to ms decrypter.
---

[RTD-426] Autoscaling Decrypter

---

src/domains/tae-common/01_keyvault.tf

This PR removes a non-working link to security logs to promote tae-common in production
---

[TAE-173] Remove link with security logs

---

src/domains/tae-app/01_network.tf
src/domains/tae-app/README.md
src/domains/tae-app/env/prod/backend.ini
src/domains/tae-app/env/prod/backend.tfvars
src/domains/tae-app/env/prod/terraform.tfvars

Promote TAE-app in production
---

[TAE-174] Create prod conf

---

src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars

This PR proposes to increase number of partitions of eventhub `rtd-platform-events` in UAT and PROD
---

[RTD-425] Increase partitions in eventhub rtd-platform-event

---

src/domains/tae-common/env/prod/terraform.tfvars
src/k8s/rtd_configmaps.tf

[TAE-175] Fix comsmos permissions

---

src/core/env/prod/terraform.tfvars
src/k8s/rtd_configmaps.tf
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars

Set many flags to enable resources in prod
---

[RTD-436] Enable resources in PROD

---

src/domains/tae-app/08_pipeline.tf

Fix Ack Ingestor Parameters
---

[RTD-435] Fix Ade Ack pipeline params

---

src/k8s/scripts/setup.sh

- added more readeble variables
- added better comments
---

k8s: fix paths and variables in scripts

---

src/domains/tae-common/env/prod/terraform.tfvars

[RTD-448] Fix cosmos throughput

---

src/core/env/dev/terraform.tfvars

New policy eventhub tkm-write-update

---

src/domains/idpay-common/04_service_bus.tf
src/domains/idpay-common/99_variables.tf
src/domains/idpay-common/README.md
src/domains/idpay-common/env/dev/terraform.tfvars

Add Azure Service Bus Queue (with auth. rule anche key-vault secret)
Use of new component Add Azure Service Bus Queue 
---

Ireer 130 creazione coda via terraform

---

src/domains/idpay-common/env/dev/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

Add idpay-errors topic
Add idpay-errors for error handling on event processing
---

IREER-132 - Add generic error topic

---

src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay_group/get-group-status.xml.tpl
src/domains/idpay-app/api/idpay_group/openapi.group.yml
src/domains/idpay-app/api/idpay_group/put-group-upload.xml.tpl

Add new API for upload file with beneficiary list
Need to upload a file with the list of beneficiary citizen for an initiative
---

IPE-195-creazione-policy-su-apim-per-esposizione-rotte-upload-file

---

src/domains/tae-common/00_monitor.tf
src/domains/tae-common/99_variables.tf
src/domains/tae-common/README.md
src/domains/tae-common/env/dev/terraform.tfvars
src/domains/tae-common/env/prod/terraform.tfvars
src/domains/tae-common/env/uat/terraform.tfvars

This PR proposes to create a TAE DB in Data Explorer Cluster
- New DB in Data Explorer Cluster
Implement an observability strategy for tae
---

[TAE-186] Add DEXP db

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/06_linked_service.tf
src/domains/tae-app/99_variables.tf
src/domains/tae-app/README.md
src/domains/tae-app/env/dev/terraform.tfvars

This PR proposes to create a linked service to access Data Explorer from Data Factory
- New linked service
- New principal assignment
This PR is useful to ingest data in Data Explorer fro Data Factory
---

[TAE-185] Add linked service for tae DB of Data Explorer

---

src/domains/tae-app/07_datasets.tf
src/domains/tae-app/README.md
src/domains/tae-app/pipelines/aggregatesIngestor.json
src/domains/tae-app/pipelines/aggregatesSchema.json
src/domains/tae-common/04_datafactory.tf

In order to support advanced metrics capabilities, aggregates must be ingested also in Dat Explorer
- New dataset representing aggregates logs
- New activity in ingestion pipeline to send aggregates to Data Explorer
Advanced Sender Monitoring
---

[TAE-180] Ingest aggregates in Data Explorer

---

src/domains/tae-app/06_linked_service.tf
src/domains/tae-app/07_datasets.tf
src/domains/tae-app/08_pipeline.tf
src/domains/tae-app/README.md
src/domains/tae-app/pipelines/ackIngestor.dataflow

This PR proposes to send acks to Data Explorer
- New Dataset
- Modify permissions of Data Factory on Data Explorer DB
Implement observability strategy
---

[TAE-181] Send acks to Data Explorer

---

src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/domains/tae-app/00_monitor.tf
src/domains/tae-app/07_datasets.tf
src/domains/tae-app/env/prod/terraform.tfvars
src/domains/tae-app/env/uat/terraform.tfvars
src/domains/tae-app/pipelines/aggregatesIngestor.json
src/domains/tae-app/scripts/create_tables.dexp
src/domains/tae-common/env/prod/terraform.tfvars
src/domains/tae-common/env/uat/terraform.tfvars

This PR proposes to modify many feature flags to promote Data Explorer in production
---

[TAE-188] Promote Data Explorer to UAT and PROD

---

src/core/env/dev/terraform.tfvars

Enabled private endpoint for ftp blob
Allow vpn connection to work as expected in DEV
---

ftp blob enabled private enpoint

---

src/domains/idpay-common/04_cdn.tf
src/domains/idpay-common/99_main.tf
src/domains/idpay-common/env/dev/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

Update CDN CSP rules
Update CDN CSP rules
---

IID-33 update cdn rule

---

src/core/api/rtd_csv_transaction/create-sas-token-policy.xml

This PR restore the hash of the key as sole variable in container name.
---

[RTD-521] Restore key hash in container name

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/08_pipeline.tf
src/domains/tae-app/99_variables.tf
src/domains/tae-app/README.md
src/domains/tae-app/env/dev/terraform.tfvars
src/domains/tae-app/env/prod/terraform.tfvars
src/domains/tae-app/env/uat/terraform.tfvars
src/domains/tae-app/scripts/create_tables.dexp

This PR proposes to create support tables in Data Explorer containing ABIs and error decoding
- A new Data Explorer table containing ABIs
- A new Data Explorer table containing error decoding
Construct advanced monitoring queries
---

[RTD-518] Create Support Tables in Data Explorer

---

src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/api/idpay_group/put-group-upload.xml.tpl
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
src/domains/idpay-app/api/idpay_initiative/post-initiative-info.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-general-draft.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-info.xml.tpl

Update iniziative API swagger and policy
Update group API swagger and policy
Update of Initiative swagger for rework on Initiative wizard
---

Ipe 376 rework swagger

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/scripts/create_tables.dexp

Alter type of two columns and reimport data
---

[RTD-561] Alter ABI table schema [Data Explorer]

---

src/domains/idpay-app/08_k8s_configmaps.tf
src/domains/idpay-app/README.md

- Removed PVC for idpay-group, this pvc will be migrated into the project
Avoid pvc that can block the terrafrom apply, and are dificult to mantain
---

Remove-persistent-volumes

---

src/aks-platform/04_rbac.tf
src/aks-platform/05_keda.tf
src/aks-platform/99_variables.tf
src/aks-platform/env/prod01/backend.ini
src/aks-platform/env/prod01/backend.tfvars
src/aks-platform/env/prod01/terraform.tfvars

- added env for aks platform on prod
setup aks platform on prod
---

feat: AKS platform on prod

---

src/domains/idpay-common/.terraform.lock.hcl
src/domains/idpay-common/04_cdn.tf
src/domains/idpay-common/04_eventhub.tf
src/domains/idpay-common/99_locals.tf
src/domains/idpay-common/README.md

storing rtd-trx topic jaas-config into idpay keyvault
---

feat: IREER-156: storing rtd-trx topic jaas-config into idpay keyvault

---

src/core/api/rtd_payment_instrument_manager/get-hash-salt_policy.xml.tpl
src/core/api_rtd.tf

This PR mock SALT call to PM which return 503 due to migration to APIM access
---

fix: [RTD-717] Mocking salt to PM 503

---

src/domains/idpay-common/05_redis_cache.tf
src/domains/idpay-common/README.md

storing redis connection string into keyvault
---

feat: storing redis connection url into keyvault

---

src/domains/tae-app/env/prod/terraform.tfvars

This PR proposes to structurally enable aggregates ingestor trigger in PROD environment.
- enable agg ingestor trigger in PROD.
This change enables the activation of the pipeline at IaaC level.
---

feat: [RTD-734] Enable aggregates ingestor trigger in PROD environment

---

src/domains/idpay-app/04_apim_api_io.tf
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl

The App IO authentication is done using a bearer token and not using an APIM subscription.
The PR:
- changes the API spec, setting a http/bearer authentication type
- remove the requirement of a subscription from the APIM api
**Please take in mind that:
- i have a limited knowledge of IDPay infrastructure/design so other changes may be required
- the same changes must be also applied to others api exposed to App IO**
---

fix: Fix App IO authentication

---

src/domains/idpay-app/01_keyvault.tf
src/domains/idpay-app/99_variables.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/env/dev/terraform.tfvars
src/domains/idpay-app/env/prod/terraform.tfvars
src/domains/idpay-app/env/uat/terraform.tfvars

fix: revoked-pi added fa namespace for prod

---

src/aks-platform/00_monitor.tf
src/aks-platform/99_locals.tf
src/aks-platform/README.md
src/core/README.md
src/core/key_vault_0.tf
src/core/observability.tf
src/domains/idpay-app/00_monitor.tf
src/domains/idpay-app/99_locals.tf
src/domains/idpay-app/README.md
src/domains/idpay-common/00_monitor.tf
src/domains/idpay-common/README.md
src/domains/rtd-app/00_monitor.tf
src/domains/rtd-app/99_locals.tf
src/domains/rtd-app/README.md
src/domains/rtd-common/00_monitor.tf
src/domains/rtd-common/README.md
src/domains/tae-app/00_monitor.tf
src/domains/tae-app/99_locals.tf
src/domains/tae-app/README.md
src/domains/tae-common/00_monitor.tf
src/domains/tae-common/README.md

feat(monitoring): [DEVOPS-465] Add new alerts channels

---

src/core/README.md
src/core/dns_private.tf

fix: [RTD-761] Added private zone link between aks platform and eventhub

---

src/aks-platform/03_aks_0.tf
src/core/network.tf

---
- inside core folder
`-target="module.k8s_snet" -target="module.adf_snet" -target="module.private_endpoint_snet"`
- inside aks-platform folder
`-target="module.snet_aks"`

fix: [RTD-821] Added eventhub service endpoint to some subnets

---

src/domains/idpay-app/.terraform.lock.hcl
src/domains/idpay-app/08_k8s_configmaps.tf
src/domains/idpay-app/99_variables.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/env/dev/terraform.tfvars
src/domains/idpay-app/env/uat/terraform.tfvars

Updated ConfigMaps for k8s
---

feat: ISB-527-modifica-config-maps-per-rilascio-uat

---

src/domains/idpay-common/env/dev/terraform.tfvars
src/domains/idpay-common/env/prod/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

Added Hpan update outcome topic
Fixed consumer group names
in order to apply in DEV, I had to run the following:
./terraform.sh import dev module.event_hub_idpay_01[0].azurerm_eventhub_consumer_group.events[\"idpay-transaction.idpay-transaction-wallet-consumer-group\"]  "subscriptions/[SUBSCRIPTION_ID]/resourceGroups/cstar-d-idpay-msg-rg/providers/Microsoft.EventHub/namespaces/cstar-[ENV_SHORT]-idpay-evh-ns-01/eventhubs/idpay-transaction/consumerGroups/idpay-transaction-wallet-consumer-group"
Resolving [SUBSCRIPTION_ID] [ENV_SHORT] vars
---

feat: IREER-178 added iban update outcome + fixed consumer group names

---

src/domains/idpay-app/api/idpay_initiative/put-initiative-approve.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-refund-draft.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-refund.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-reject.xml.tpl

Change initiative policy API in order to add organization name in payload
Change initiative policy API in order to add organization name in payload to complete email notification field
---

feat: IPE-515-aggiornamento-policy-per-informazioni-di-organizzazione

---

src/domains/idpay-common/03_database.tf

Add collection for initiative statistics
Add collection for initiative statistics
---

feat: IPE-481 add new initiative_statistics collection

---

src/domains/rtd-app/04_eventhub.tf
src/domains/rtd-app/README.md

feat: [RTD-762] Added eventhub connection string to rtd-kv

---

src/k8s/README.md
src/k8s/rtd_secrets.tf
src/k8s/secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/k8s/variables.tf

chore: [RTD-762] Providing jaas connection string as k8s secrets from new kv

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/scripts/create_tables.dexp

This pr proposes to add a new Table "Sender" in data explorer
---

feat: [RTD-792] Add Sender Table

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/README.md

This PR proposes to add an alert on malformed chunks found by decrypter.
- add alert
- update doc
Whenever at least one chunk of an input file is malformed no chunks will be uploaded.
With this change we can be notified and take actions. 
```
--target="azurerm_monitor_scheduled_query_rules_alert_v2.not_all_chunks_are_verified_decrypter[0]"
```
---

feat: [RTD-813] Add malformed chunk alert

---

src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl

Add fallback on real BE IO on token IO validation
Need to test with mocked and real token IO
---

feat: IID-45 Add token validation to BE IO only for UAT

---

src/domains/tae-app/08_pipeline.tf
src/domains/tae-app/README.md

This PR proposes to enable Diagnostic Settings on Azure Data Factory.
- enable diagnostic settings on adf with PROD log analytics as workspace.
With this change we can monitor granularly the pipeline failures.
```
--target="azurerm_monitor_diagnostic_setting.acquirer_aggregate_diagnostic_settings[0]" 
```
---

feat: [RTD-771] Enable diagnostic settings on TAE Azure Data Factory

---

src/domains/idpay-common/01_keyvault_external_secrets.tf
src/domains/idpay-common/99_variables.tf
src/domains/idpay-common/README.md
src/domains/idpay-common/env/dev/terraform.tfvars
src/domains/idpay-common/env/prod/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

feat: [RTD-856] Provisioning rtd eventhub connection string to idpay kv

---

src/core/env/prod/terraform.tfvars
src/core/rtd_database.tf

This PR proposes to create an index on field `name` in `fileregister` collection
- New index
Optimize queries
---

chore: [RTD-899] Add index on name (fileregister)

---

src/domains/idpay-app/01_keyvault.tf
src/domains/idpay-app/README.md

- add appinsight instrumentation key secrets to key vault by terraform
---

fix: [RTD-934] Fix missing idpay secrets

---

src/core/README.md
src/core/api/rtd_payment_instrument_manager/get-hashed-pans-policy-rev3.xml.tpl
src/core/api_rtd.tf

This PR expose a v3 hashpan endpoint to get hashpan/par file
- payment instrument api v3 
---

feat: [RTD-805] Add hashpan v3 to get hashpan/par tuples

---

src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl

change app io hostname
update configuration in order to use the new be io hostname
---

feat: IGR-69 update hostname io

---

src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/09_refund_storage.tf

moved secret values of refund into its file
no changes
---

chore: IDPAY-moved secret values of refund into its file

---

src/core/api/rtd_payment_instrument_token/openapi.yml
src/core/api/rtd_payment_instrument_token/upload-token-file-policy.xml
src/core/api_rtd.tf

This PR adds a new endpoint to upload tokenpan files from batch service or through acquirer api
- new POST `rtd/token/token-list` api to upload tokenpan file
---

feat: [RTD-682] Expose Acquirer API to upload tokenpan files 

---

src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl

- Move oneOf union in a dedicated schema (semantically equal but needed for a limitation of our code generator)
For a limitation in the TS codegen is required to extract the oneOf union to a dedicated schema
---

feat: Adapt the timeline API to support TS codegen

---

src/core/README.md
src/core/api/rtd_payment_instrument_token/get-known-hashes-policy.xml
src/core/api/rtd_payment_instrument_token/openapi.yml
src/core/api/rtd_payment_instrument_token/upload-token-file-policy.xml
src/core/api_rtd.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/variables.tf

This PR expose a new endpoint to get known hashes (aka solved tokenpans) from TKM 
---

feat: [RTD-923] Add API to get known hashes from TKM

---

src/core/api/rtd_payment_instrument_token/get-bin-range-policy.xml
src/core/api/rtd_payment_instrument_token/openapi.yml
src/core/api_rtd.tf

This PR expose bin range get endpoint.
- added '/bin-ranges/link' api to take bin ranges from TKM
---

feat: [RTD-628] Expose bin range api

---

src/core/api_product/rtd_api/policy.xml

This PR proposes to check if caller has a valid client certificate
---

fix: [RTD-1029] Add check header policy on rtd api product

---

src/domains/rtd-app/08_k8s_configmaps.tf
src/domains/rtd-app/99_variables.tf
src/domains/rtd-app/README.md
src/domains/rtd-app/env/dev/terraform.tfvars
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars

This PR copy sender auth config map to new aks for DEV and UAT env. Also adds feature flags
---
`-target="kubernetes_config_map.rtdsenderauth"`

chore: [RTD-1048]: SenderAuth config map to new aks

---

src/domains/idpay-app/04_apim_api_io.tf

Use versionless secret ID in named value
---

fix: Use versionless secret ID

---

src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars

fix: missing ingress variables

---

src/core/api_pm.tf

fix: Use versionless id pm api key

---

src/domains/rtd-app/08_k8s_configmaps.tf
src/domains/rtd-app/99_variables.tf
src/domains/rtd-app/README.md
src/domains/rtd-app/env/dev/terraform.tfvars
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars

chore: [RTD-1056]add pi-event-processor configmaps + common ones

---

src/aks-platform/env/prod01/terraform.tfvars

fix: fix location string

---

src/domains/rtd-app/08_k8s_configmaps.tf
src/domains/rtd-app/99_variables.tf
src/domains/rtd-app/README.md
src/domains/rtd-app/env/dev/terraform.tfvars
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars

This PR adds enrolled pim related configmaps to new aks (domain rtd)
---

chore: [RTD-641] Add configmap for enrolled pim to new aks

---

src/core/README.md
src/core/api_rtd.tf
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars
src/k8s/README.md
src/k8s/rtd_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars

This PR create a new api key named value for platform pagopa apim TKM's product. Also fixes all named value occurrences inside RTD apim polices.
---
`-target="module.rtd_payment_instrument_token_api" -target="azurerm_api_management_named_value.tkm-sas-token" -target="azurerm_api_management_named_value.pagopa_platform_apim_key" -target="azurerm_api_management_named_value.pagopa_platform_api_tkm_key" -target="azurerm_api_management_named_value.pagopa_platform_api_primary_key_tkm"`
inside k8s folder:
`-target="kubernetes_secret.pagopa_platform_api_key_tkm" -target="kubernetes_secret.pagopa_platform_api_key"`

fix: [RTD-1171] updated apim tkm api key

---

src/domains/rtd-app/08_k8s_configmaps.tf
src/domains/rtd-app/99_variables.tf
src/domains/rtd-app/README.md
src/domains/rtd-app/env/dev/terraform.tfvars
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars

This PR adds file-register configmaps to new aks
---

chore: [RTD-1073] Add file-register configmaps to new aks

---

src/domains/rtd-app/08_k8s_configmaps.tf
src/domains/rtd-app/README.md

chore: [RTD-1069] Fix wrong ingestor as k8s secret

---

src/domains/rtd-app/08_k8s_configmaps.tf
src/domains/rtd-app/README.md

This PR adds file register project consumer config map to new aks
---

chore: [RTD-1079] Add file-register-projector-consumer config map

---

src/core/api/rtd_filereporter/get-file-report-policy.xml.tpl
src/core/api_rtd.tf

This PR updates file report ingress usage to new aks url
---
`-target="module.rtd_filereporter"`

chore: [RTD-1082] Update filereport ingress url to new aks

---

src/core/.terraform.lock.hcl
src/core/99_outputs.tf
src/core/README.md
src/core/dns_public.tf

feat: New public dns zone welfare

---

src/core/.terraform.lock.hcl
src/core/rtd_database.tf
src/k8s/.terraform.lock.hcl

Add index for hashPanChildren inside payment instrument cosmo db
---

chore: [RTD-1159] added index in rtd_database

---

src/domains/tae-app/scripts/create_tables.dexp

fix: [RTD-1201] Align create table script with current schema

---

src/core/rtd_database.tf
src/domains/idpay-common/README.md

This PR proposes to align the settings on the max_throughput on the sender-auth collection. The changes are already applied.
---

chore: [RTD-1250] set max throughput on sender-auth collection

---

src/core/README.md
src/core/sftp.tf
src/domains/tae-common/04_datafactory.tf
src/domains/tae-common/README.md

fix: [RTD-1271] Align sftp threat protection

---

src/core/README.md
src/core/storage.tf

fix: [RTD-1272] Align threat protection on acquirer storage account

---

src/core/README.md
src/core/storage.tf

fix: [RTD-1273] Align threat protection on backup storage account

---

src/core/observability.tf

fix: [RTD-1275] Alignment of Diagnostic Settings' APIM on core

---

src/domains/rtd-app/pipelines/hashpan_csv_pipeline.json
src/domains/rtd-app/pipelines/hashpan_par_csv_pipeline.json

chore: [RTD-1276] Align Terraform code of HPANs pipeline on rtd-app

---

src/core/99_outputs.tf
src/core/README.md
src/core/aks.tf
src/core/observability.tf

In order to enable azure policies, this PR proposes to align old k8s module to 4.3.0 azurerm repo version.
---

fix: [RTD-1274] Enable azure policies on aks

---

src/core/README.md
src/core/storage.tf

fix: [RTD-965] Enable threat protection

---

src/core/99_outputs.tf
src/core/README.md
src/core/network.tf

feat: New app gateway multi az

---

src/core/README.md
src/domains/tae-common/02_blob_storage.tf

This PR proposes to align the account storage diagnostic settings with the portal settings.
- update diagnostic settings resources
The plan in all environments proposes to change the log destination type in LAW and this behaviour is unwanted.
---

chore: [RTD-1289] align account storage diagnostic settings

---

src/core/README.md
src/core/observability.tf

This PR proposes to enable Diagnostic Setting on new Application Gateway.
- enable Diagnostic Setting on new Application Gateway.
With this change we can gather new AppGW logs in Log Analytics Workspace. Analyzing those logs we can receive alerts like we currently do for the old AppGW.
```
-target=azurerm_monitor_diagnostic_setting.appgw_maz_diagnostic_settings
```
---

feat: [RTD-1283] Enable Diagnostic settings on AppGW multi-availability zone

---

src/domains/tae-common/env/dev/terraform.tfvars
src/domains/tae-common/env/prod/terraform.tfvars
src/domains/tae-common/env/uat/terraform.tfvars

This PR proposes to align the soft delete period setting on kusto data explorer.
- change format to days
The plan proposes to make this change in all envs, this PR will align the code.
---

chore: [RTD-1291] align kusto soft delete period setting

---

src/core/api_rtd.tf

chore: align fake salt to dev and uat env, also remove mock from v3

---

src/domains/tae-common/04_datafactory.tf

This PR proposes to align the fqdns settings on data factory private endpoints.
- update data factory private endpoint resources
---

chore: [RTD-1290] explicitly set fqdns on data factory private endpoints

---

src/domains/idpay-app/env/uat/terraform.tfvars

Update IO endpoint for UAT
Need to call real IO API for Demo purposes
---

feat: IDP-344 update BE di IO

---

src/k8s/.terraform.lock.hcl
src/k8s/99_main.tf
src/k8s/README.md
src/k8s/rtd_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars

fix: align k8s

---

src/core/README.md
src/core/storage.tf

chore: [RTD-965] Remove storage account psqlinfra

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl

Changed ErrorDto to ErrorDTO in onboarding swagger and merged swagger
Changed InitiativeDto to InitiativeInfoDTO in onboarding swagger and merged swagger
The old naming generated conflicts and caused problems to client codegen
---

fix: [IDP-349] fixed merged swagger

---

src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl

This PR proposes to use a suffix to make token key unique in APIM cache
---

fix: IDPAY_IO_APP Product Policy

---

src/domains/tae-common/00_azuread.tf
src/domains/tae-common/04_datafactory.tf
src/domains/tae-common/README.md

This PR proposes to add a custom role to run ADF Pipelines and assigns the role to operations Active Directory froup
---

chore: [RTD-1367] Add custom role and custom role assignment to ops

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl

Added accrued as required in timeline
---

feat: [IDP-397] Updated swagger

---

src/core/README.md
src/core/api_cdc.tf

This PR "terraformize" cdc certification generation while setup it to apim for UAT environment
- add certificate generation on KV for UAT and PROD
- add certificate to APIM for UAT and PROD
- update UAT policy to use new certificate
Target: 
```
```
---

chore: [CDC-80] Add CDC certificate generation

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl

Removed accrued field from Timeline Refund
Target: 
```
```
---

fix: removed accrued field from Timeline Refund

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl

Updated 403 errors on onboarding API + fixed required field on wallet
Target: 
```
-target=module.idpay_onboarding_workflow_io -target=module.idpay_wallet_io -target=module.idpay_onboarding_workflow_issuer -target=module.idpay_wallet_issuer
```
---

feat: updated swagger for wallet api

---

src/core/variables.tf

feat: redirect apim to new aks ingress prod

---

src/core/network.tf

This PR proposes to add a rewrite rule in App Gateway to add a custom header for the client certificate end date.
- Add rewrite rule
In order to keep track and alert the expiring certificates we need to add a custom header and log it on APIM.
Target: 
```
module.app_gw_maz
```
---

chore: [RTD-1465] add custom header for certificate end date

---

src/core/env/uat/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

Increased partition number for some idpay topics
Performance
Target: 
```
```
---

feat: [IDP-58] Partition tuning

---

src/core/env/uat/terraform.tfvars

rtd-trx partitions from 1 to 16 in uat
Target: 
```
```
---

feat: [IDP-500] changed partitions on rtd-trx

---

src/core/api_cdc.tf

chore: [RTD-80] enable new cert in prod for cdc

---

src/domains/idpay-common/env/uat/terraform.tfvars

Target: 
``` 
-target=module.mongdb_collections -target=azurerm_key_vault_secret.cosmosdb_account_mongodb_connection_strings
```
---

fix: Set provisioned throughput on UAT cosmos

---

src/domains/rtd-common/04_eventhub.tf

This PR rewrite order of virtual network rules by following the order proposed by azure/terraform delta detection
Target: 
```
```
---

chore: relaxing eventhub virtual network rules order

---

src/aks-platform/03_aks_0.tf

This PR proposes to add the service endpoint related to AzureCosmosDB to the cluster k8s subnet.
Target: 
```
module.snet_aks 
```
---

feat: [RTD-1512] add service endpoint for cosmos on k8s subnet

---

src/core/env/uat/terraform.tfvars

fix: Enable cosmos SSR in UAT

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/README.md

This PR proposes to add an alarm on the client certificate expiry date.
- add alarm
Target: 
```
```
---

feat: [RTD-1509] add alarm on client certificate expiry date

---

src/aks-platform/03_aks_0.tf
src/domains/idpay-common/00_network.tf
src/domains/idpay-common/03_database.tf
src/domains/idpay-common/99_variables.tf
src/domains/idpay-common/README.md
src/domains/idpay-common/env/dev/terraform.tfvars
src/domains/idpay-common/env/prod/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

This PR proposes to add a private endpoint to the cosmos resource and to restrict the access only to k8s subnet to grant the microservices to access the db.
- added private endpoint
- added list of allowed subnet to cosmos
Target: 
```
module.cosmosdb_account_mongodb
```
---

feat: [RTD-985] add private endpoint on idpay cosmos

---

src/core/README.md
src/core/messages.tf

fix: Eventhub v4.13.2 version module

---

src/domains/rtd-app/08_pipeline.tf
src/domains/rtd-app/99_variables.tf
src/domains/rtd-app/README.md
src/domains/rtd-app/env/dev/terraform.tfvars
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars

This PR removes hpan/par pipeline from ADF.
- removed trigger
- removed datasets
- removed pipeline
Target: 
```
```
---

chore: [RTD-1504] Remove hpan par adf pipeline

---

src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
src/domains/idpay-app/api/idpay_initiative/put-initiative-suspension.xml.tpl
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl

added new policy
user suspension
Target: 
```
```
---

feat: [IDP-593] added policy for suspension

---

src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
src/domains/idpay-app/api/idpay_initiative/put-initiative-readmission.xml.tpl
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl

Add new policy
User readmission
Target: 
```
```
---

feat: IDP-657-censimento-apim

---

src/domains/idpay-app/api/idpay_qrcode_payment/acquirer/openapi.qrcode_payment_acquirer.yml.tpl
src/domains/idpay-app/api/idpay_qrcode_payment/io/openapi.qrcode_payment_io.yml.tpl

feat: Idp 752 update swagger idpay payment

---

src/domains/tae-app/00_monitor.tf

This PR proposes to set evaluation frequency and window to 1 day from 5 minutes.
- change alert parameters.
With this change we reduce the noise produced by senders that don't update the Batch Service.
Target: 
```
azurerm_monitor_scheduled_query_rules_alert_v2.deprecated_batch_service_version
```
---

fix: [RTD-1638] Change deprecation alert frequency and window to 1 day

---

src/domains/idpay-common/04_cdn.tf
src/domains/idpay-common/99_variables.tf
src/domains/idpay-common/README.md

mock merchant SPA rewrite URL rule configuration
Target: 
```
```
---

feat: IDP-721 mock merchant SPA

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl

fix api timeline
fix api timeline
Target: 
```
```
---

fix: [IDP-722] fix enum operationType

---

src/domains/idpay-app/08_k8s_configmaps.tf

Updated k8s configmap to set idpay-reward-calculator service url
Target: 
```
```
---

feat: IDP-616 Updated k8s configmap to set idpay-reward-calculator service url

---

src/aks-platform/00_network.tf
src/aks-platform/03_aks_dns_private_link.tf
src/aks-platform/99_locals.tf
src/aks-platform/99_variables.tf
src/aks-platform/README.md
src/aks-platform/env/dev01/terraform.tfvars
src/aks-platform/env/prod01/terraform.tfvars
src/aks-platform/env/uat01/terraform.tfvars
src/core/.terraform.lock.hcl
src/core/README.md
src/core/dns_private.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/network.tf
src/core/network_pair.tf
src/core/storage.tf
src/core/variables.tf
src/core/vpn.tf

- created new dns forwarder (container instance) in northeurope
- created new vnet in north europe
- created vnet peering for the new vnet
- created dns private link for the new vnet
Allow to have a dns forwarder in the pair region to avoid problems
Target: 
```
```
---

breaking: Created DNS forwarderd in northeurope for DR

---

src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/storage.tf
src/core/variables.tf

- Added variables for cstarblobstorage storage replication type
- Allow each env to have a different configuration of storage replication type
Target: 
```
```
---

fix: Added variables for cstarblobstorage storage replication type

---

src/domains/idpay-common/03_database.tf

IDP-619 refactor user_initiative_counters indexes
added new mongo collection transaction_in_progress
updated mongo collection user_initiative_counters indexes
Target: 
```
```
---

feat: IDP-628 IDP-619 mongo collection updates

---

src/core/network_aks_domains.tf
src/core/network_pair.tf

Allow dns forwarder in north europe to work as expected
Target: 
```
```
---

feat: Allow Traffic forwarded from remote virtual network for pair network

---

src/core/env/dev/terraform.tfvars

This PR proposes to fulfill the tech debt left by migration to v3 modules about the public key api. In particular the check on the last supported version of batch service is involved.
Target: 
```
module.rtd_csv_transaction
```
---

fix: [RTD-1620] batch service last supported version to 1.3.2

---

src/domains/rtd-common/.terraform.lock.hcl
src/domains/rtd-common/01_keyvault_0.tf
src/domains/rtd-common/04_datafactory.tf
src/domains/rtd-common/99_main.tf
src/domains/rtd-common/README.md

This PR migrate rtd-common to azurerm v3
- keyvault module bump to azurermv3
- removed useless resource group name on adf runtime resource
Target: 
```
```
---

chore: [RTD-1599] Bump to azurerm v3

---

src/domains/idpay-common/03_database.tf

Added index eventId on timeline collection
Target: 
```
```
---

feat: IDP-909 added index eventId on timeline collection

---

src/domains/idpay-app/08_k8s_configmaps.tf

Changed configmap rest-client
Target: 
```
```
---

feat: IDP-982 added admissibility assessor to rest-client config map

---

src/domains/idpay-common/99_variables.tf
src/domains/idpay-common/README.md

configuring new PortaleEsercenti SPA
Target: 
```
```
---

feat: IDP-960 configuring new PortaleEsercenti SPA

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl

fix response unsubscribe
Target: 
```
```
---

fix: fix response unsubscribe api

---

src/core/README.md
src/core/messages.tf

This PR bumps eventhub module to latest which supports firewall bypass for microsoft trusted service (like eventgrid)
Target: 
```
```
---

chore: [RTD-1668] Update eventhub module core to support trustes microservices

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml
src/domains/idpay-app/api/idpay_timeline/openapi.timeline.yml.tpl
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl

updated swagger openapi.appio.full.yml, openapi.wallet.yml, openapi.wallet.yml.tpl, remove field
because in idpay-wallet "initiativeDTO" has been removed maxTrx field
Target: 
```
```
---

fix: IDP-967 remove maxTrx field

---

src/domains/idpay-app/04_apim_api_merchants_token_exchange.tf
src/domains/idpay-app/04_apim_api_portal_merchants.tf
src/domains/idpay-app/04_apim_api_token_exchange_merchants.tf
src/domains/idpay-app/06_apim_fragments.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay_token_exchange/jwt_exchange_merchants.xml.tpl
src/domains/idpay-app/api_fragment/merchant-id-retriever.xml
src/domains/idpay-app/api_product/acquirer/policy_acquirer.xml
src/domains/idpay-app/api_product/portal_merchants_api/policy_merchants_portal.xml.tpl

Added JWT keys generation + new tokenExchange API to build MerchantPortal JWT + MerchantPortalProduct
Target: 
```
```
---

feat: IDP-964 IDP-963 portale esercenti token exchange

---

src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay_merchant/get-merchant-detail-policy.xml.tpl
src/domains/idpay-app/api/idpay_merchant/get-merchant-list-policy.xml.tpl
src/domains/idpay-app/api/idpay_merchant/openapi.merchant.yml
src/domains/idpay-app/api/idpay_merchant/openapi.merchant.yml.tpl
src/domains/idpay-app/api/idpay_merchant/put-merchant-upload.xml.tpl

Added policy for new merchant api
Target: 
```
```
---

feat: Idp 941 censimento policy su apim e archiviazione storage

---

src/domains/idpay-app/04_apim_api_portal_merchants.tf
src/domains/idpay-app/04_apim_api_token_exchange_merchants.tf

fixed Idpay Merchant APIm path
Target: 
```
```
---

fix: IDP-964 fixed idpay merchant path

---

src/core/database.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars

fix: Disable FA postgres in dev and uat. Clean code

---

src/core/README.md
src/core/dns_public.tf

feat: Add CAA record

---

src/domains/idpay-app/80_tls_checker.tf
src/domains/idpay-app/99_variables.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/env/dev/terraform.tfvars
src/domains/idpay-app/env/prod/terraform.tfvars
src/domains/idpay-app/env/uat/terraform.tfvars
src/domains/rtd-app/.terraform.lock.hcl
src/domains/rtd-app/80_tls_checker.tf
src/domains/rtd-app/99_variables.tf
src/domains/rtd-app/README.md
src/domains/rtd-app/env/dev/terraform.tfvars
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars
src/domains/tae-app/05_aks_middleware_tools.tf
src/domains/tae-app/99_variables.tf
src/domains/tae-app/README.md
src/domains/tae-app/env/dev/terraform.tfvars
src/domains/tae-app/env/prod/terraform.tfvars
src/domains/tae-app/env/uat/terraform.tfvars

added cert mounter module to all app domains
Target: 
```
```
---

feat: Added cert mounter

---

.devops/idpay-code-review-pipelines.yml
src/packer/README.md

fix: azdo-pipelines typos

---

README.md
src/domains/rtd-app/04_api_rtd.tf

Null PR to run Release Job 
Target: 
```
```
---

fix: add space to launch release

---

src/domains/idpay-app/11_workbooks.tf
src/domains/idpay-app/workbooks/OPEXWorkbook.json.tpl

feat: IDP-1005_workbook_opex

---

src/domains/idpay-common/03_database.tf

nex index in transaction_in_progress_collection
Target: 
```
```
---

fix: added index in transaction_in_progress collection

---

src/domains/idpay-app/08_k8s_configmaps.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/k8s-file/appinsights-config/applicationinsights.json

Added configmap for application insights config
Configuration application insights
Target: 
```
```
---

feat: IDP-1170 add appsingihts config-map from file

---

src/core/README.md
src/core/dns_private.tf
src/core/network.tf
src/core/sftp.tf

feat: Added redis dns zone

---

src/core/README.md
src/core/sftp.tf

feat: Add container and dirs for Consap

---

src/core/env/prod/terraform.tfvars

fix: Add old consap IP to SFTP  whitelist

---

src/k8s/bpd_secrets.tf
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars

fix: Customize bpd notificator SFTP account

---

src/core/sftp.tf

fix: Fix dirs

---

src/k8s/README.md
src/k8s/fa_secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars

fix: Restore secrets for io-mock

---

src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl
src/domains/idpay-app/api_product/app_issuer/policy_issuer.xml.tpl

fix fiscal code exception code
Target: 
```
```
---

fix: [IDP-938] new exception code for fiscal code not valid

---

src/domains/idpay-app/04_apim_api_portal_merchants.tf
src/domains/idpay-app/api/idpay_merchants_portal/get-merchant-transactions-processed-policy.xml.tpl
src/domains/idpay-app/api/idpay_merchants_portal/openapi.merchants.portal.yml
src/domains/idpay-app/api/idpay_merchants_portal/openapi.merchants.portal.yml.tpl
src/domains/idpay-app/api/idpay_qrcode_payment/acquirer/openapi.qrcode_payment_acquirer.yml.tpl
src/domains/idpay-app/api/idpay_qrcode_payment/acquirer/openapi.qrcode_payment_test_merchant.yml.tpl

Fix swagger for merchant portal and added new api for transactions processed list
Target: 
```
```
---

feat: [IDP-1218] edit swagger payment/merchant

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_qrcode_payment/io/openapi.qrcode_payment_io.yml.tpl

feat: IDP-1165 swagger io cancel payment

---

.devops/core-code-review-pipelines.yml
.devops/idpay-code-review-pipelines.yml
.devops/rtd-code-review-pipelines.yml
.devops/tae-code-review-pipelines.yml

Try Autocancel in pipelines, to avoid code reviews for olds commits
Target: 
```
```
---

feat: Pipelines code review with autoCancel = true

---

src/domains/idpay-app/api/idpay_merchants_portal/get-merchant-transactions-processed-policy.xml.tpl

fix policy for merchant
Target: 
```
```
---

fix: fix policy list transaction processed

---

src/domains/idpay-app/12_alert.tf
src/domains/idpay-app/README.md

Add alert CreateTransaction
Update alert CosmosServerSideRetry
Target: 
```
```
---

feat: IDP-1116 generazione-qr-code-magic-link-portale-esercenti

---

src/core/win_terraform.sh
src/domains/idpay-app/win_terraform.sh
src/domains/idpay-common/03_database.tf
src/domains/idpay-common/win_terraform.sh
src/domains/rtd-app/win_terraform.sh
src/domains/rtd-common/win_terraform.sh
src/domains/tae-app/win_terraform.sh
src/domains/tae-common/win_terraform.sh
src/domains/welfare/win_terraform.sh

feat: IDP-1244_rimozione_indice_onboarding_citizen

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml

fix swagger
- [] Yes, users may be impacted applying this change
Target: 
```
```
---

fix: [IDP-1281] fix swagger IO

---

src/domains/tae-app/01_monitor_incident.tf

chore: [RTD-1748] add link to opsgenie for external access problems alert

---

src/domains/idpay-app/04_apim_api_portal_merchants.tf
src/domains/idpay-app/api/idpay_notification_email/get-institution-user-info-merchant-policy.xml.tpl

Added merchant policy for get institution users 
Target: 
```
-target=module.idpay_merchants_notification_email_api
```
---

feat: [IDP-1153] added new merchant policy for get institution users

---

src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml

Fix authority code
This pull request allows the creation of initiatives with one of the authority codes that App IO expects (modeled as an enumeration in full swagger).
Target: 
```
```
---

fix: [IDP-1350] fix authority code

---

src/domains/idpay-common/03_database.tf

Change index collection
Target: 
```
```
---

fix: IDP-1358 change index

---

src/core/README.md
src/core/dns_private.tf

This PR add a private dns zone link to new aks vnet. 
This fix allows k8s pods to resolve names under privatelink.blob.core.windows.net dns zone.
Target: 
```
```
---

fix: Add blob private zone virtual link to aks vnet

---

src/domains/idpay-common/03_database.tf

added new indexes in wallet collection
Target: 
```
module.mongdb_collections
```
---

feat: IDP-1411 added new indexes in wallet db

---

src/domains/idpay-common/03_database.tf

added new indexes in payment_instrument collection
Target: 
```
module.mongdb_collections
```
---

feat: IDP-1413 added new indexes in payment_instrument collection

---

src/domains/rtd-app/06_linked_service.tf
src/domains/rtd-app/README.md

fix: Remove useless linked services

---

src/core/env/dev/terraform.tfvars
src/core/env/uat/terraform.tfvars

feat: remove bpd db in dev and uat

---

src/core/env/dev/terraform.tfvars
src/core/env/uat/terraform.tfvars

fix: Remove BPD APIs uat dev

---

src/k8s/fa_configmaps.tf
src/k8s/fa_ingress.tf
src/k8s/fa_secrets.tf
src/k8s/namespaces.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars

fix: Remove residual configs FA

---

src/domains/idpay-common/03_database.tf

fix: [IDP-1563] Add hpan as index of payment_instrument

---

src/domains/rtd-app/04_eventhub.tf
src/domains/rtd-app/env/dev/terraform.tfvars
src/domains/rtd-app/env/prod/terraform.tfvars
src/domains/rtd-app/env/uat/terraform.tfvars

This PR create rtd-platform-events queue to rtd eventhub namespace
Target: 
```
```
---

chore: [RTD-1868] Create rtd-platform-events to rtd eventhub

---

src/acr/README.md
src/acr/acr-clean-domain.sh
src/acr/acr-clean-image.sh

chore:  [RTD-1839] Add cleaning acr script

---

src/domains/tae-app/00_key_vault.tf
src/domains/tae-app/01_monitor_incident.tf
src/domains/tae-app/99_variables.tf
src/domains/tae-app/README.md
src/domains/tae-app/env/prod/terraform.tfvars

This PR is about to add in adein inc description a reference to the relative runbook.
Target: 
```
```
---

chore: [RTD-1844] add runbook for adein problems

---

src/domains/idpay-common/03_database.tf

Add indexes 'retry' and 'retryDate' to the collection Notification
Target: 
```
```
---

feat: IDP-1448_analisi_sugli_indici_su_collection_notification

---

src/core/env/dev/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/events.tf
src/core/sftp.tf

This PR will remove rtd-platform-events hub from dev & uat, while keep it active in PROD
Target: 
```
```
---

chore: [RTD-1826] Remove rtd-platform-events for dev & uat

---

src/domains/tae-app/01_monitor_incident.tf

fix: [RTD-1908] fix decrypter incident description typo

---

src/domains/idpay-common/03_database.tf

renamed index from userId to entityId
Target: 
```
idpay-common -target=module.mongdb_collections
```
---

feat: [IDP-1469] adeguare-user-initiative-counters-per-nuclei

---

src/core/README.md
src/core/dns_public.tf

This PR proposes to add a CAA record to welfare dns server
Target: 
```
```
---

fix: Add CAA record to welfare dns

---

src/domains/idpay-common/env/prod/terraform.tfvars

fix: Set Redis SKU to Standard in PROD

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl

Added 401 exception to wallet /wallet/{initiativeId}/detail api.
Modified swagger io full accordingly.
The api /wallet/{initiativeId}/detail was missing the 401 exception
Target: 
```
```
---

fix: IDP-1645-Added 401 exception to wallet swagger api, modified swagger io full accordingly

---

src/core/README.md
src/core/storage.tf

Add a container to store data cold backup
Target: 
```
```
---

feat: Add container cold bkp db

---

src/domains/idpay-common/03_database.tf

Added index on the field 'userId' in the collection hpan_initiatives_lookup
This change decreases the cost(RU) of the query setUserInitiativeStatus()
Target: 
```
```
---

feat: IDP-1446-analizzare-il-costo-delle-query-sulla-collection-hpan-initiatives-lookup

---

src/domains/rtd-app/04_eventhub.tf
src/domains/rtd-app/08_k8s_configmaps.tf
src/domains/rtd-app/env/dev/terraform.tfvars

This PR removes migration-pi queue from dev environment
Target: 
```
```
---

chore: [RTD-1936] Remove migration-pi queue

---

src/domains/idpay-app/api/idpay_merchant/put-merchant-upload.xml.tpl

Fixed the rewrite of the merchant upload api.
Target: 
```
module.idpay_merchant_portal
```
---

fix: fix merchant upload api

---

src/domains/idpay-app/api/idpay_assistance/openapi.assistance.yml
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml

- add familyId in object onboardingRanking for api /ranking/exports
Target: 
```
module.idpay_api_assistance
module.idpay_initiative_portal
```
---

fix: [IDP-1761] added familyId in OnboardingRankingsDTO

---

src/domains/idpay-app/09_initiative_storage.tf
src/domains/idpay-app/README.md

Add role to policy for download ranking
Target: 
```azurerm_role_assignment.initiative_storage_data_contributor
```
---

fix: [IDP-1762] fix role

---

src/aks-platform/env/prod01/terraform.tfvars
src/domains/idpay-app/02_namespace_domain.tf
src/domains/rtd-app/02_namespace_domain.tf

- aks prod upgrated to 1.25.11
- middleware aks upgrated to support 1.25
Aks upgrated to 1.25.11 
Target: 
```
```
---

breaking: Aks PROD upgrade to 1.25 and middleware upgrade

---

src/domains/idpay-app/04_apim_api_acquirer.tf
src/domains/idpay-app/04_apim_api_assistance.tf
src/domains/idpay-app/04_apim_api_io.tf
src/domains/idpay-app/04_apim_api_issuer.tf
src/domains/idpay-app/04_apim_api_mil.tf
src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/04_apim_api_portal_merchants.tf
src/domains/idpay-app/99_locals.tf

Target: 
```
-target="module.idpay_timeline_io" -target="module.idpay_wallet_issuer" -target="module.idpay_timeline_issuer" -target="module.idpay_wallet_io" -target="module.idpay_merchant_portal" -target="module.idpay_merchants_notification_email_api" -target="module.idpay_notification_email_api"
```
---

chore: [RTD-1991] HTTPS for calls to ingress k8s

---

src/domains/idpay-app/04_apim_api_mock.tf
src/domains/idpay-app/08_k8s_configmaps.tf
src/domains/idpay-app/99_variables.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay_mock_api/mock_delete_service.xml.tpl
src/domains/idpay-app/env/dev/terraform.tfvars
src/domains/idpay-app/env/prod/terraform.tfvars
src/domains/idpay-app/env/uat/terraform.tfvars

- added new variable io_manage_backend_base_url
- added mocked API to delete service io in dev environment
Target: 
```
kubernetes_config_map.rest-client
azurerm_api_management_api_operation.idpay_mock_delete_service
azurerm_api_management_api_operation_policy.idpay_mock_delete_service_policy
```
---

feat: [IDP-1812] new variable and mock added to delete service IO

---

src/domains/idpay-app/04_apim_api_acquirer.tf
src/domains/idpay-app/04_apim_api_assistance.tf
src/domains/idpay-app/04_apim_api_io.tf
src/domains/idpay-app/04_apim_api_issuer.tf
src/domains/idpay-app/04_apim_api_mock_merchant.tf
src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/04_apim_api_portal_merchants.tf
src/domains/rtd-app/04_api_rtd.tf

chore: [RTD-1991] allows only https apim protocols

---

src/domains/idpay-app/api/idpay_mil/openapi.mil.yml
src/domains/idpay-app/api_product/mil_api/policy_mil.xml

- added check if header "x-acquirer-id" in policy for MIL product. If it is not present then an error is returned
Target: 
```
idpay_mil
idpay_api_mil_product
```
---

fix: [IDP-1751] strengthened check over the header acquirerId for api MIL 

---

src/core/api.tf
src/core/api_bpd.tf
src/core/api_pm.tf

chore: [RTD-1991] Enforce https apim bpd

---

src/domains/idpay-app/api/idpay_assistance/openapi.assistance.yml
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml

- Added familyId in api getOnboardingList
When the initiative is for family unit then in the list of onboardings it can be seen the familyId to which the user belongs.
Target: 
```
module.idpay_initiative_portal
module.idpay_api_assistance
```
---

fix: [IDP-1824] added familyId in onboardingList

---

src/core/README.md
src/core/observability.tf

- removed log analytics from subscription
Allow to manage subscription log analytics to azure policy
Target: 
```
```
---

feat: RTD-2088 Removed log analytics managed by policy

---

src/core/README.md
src/core/aks.tf
src/core/variables.tf

Remove old aks alarms
Target: 
```
```
---

fix: Remove aks alarms

---

src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars

Fix blob soft delete
Target: 
```
```
---

fix: Rtd 970 increase soft delete days prod

---

src/domains/idpay-app/api/idpay_mock_citizen_data/create-isee-policy.xml.tpl
src/domains/idpay-app/api/idpay_mock_citizen_data/openapi.mock.citizen.yml

Moved INPS isee mock endpoint
Target: 
```
```
---

feat: IDP-1860 inps mock moved

---

src/domains/idpay-app/01_keyvault.tf
src/domains/idpay-app/README.md

IDP-1914: mil and idpay RSA key generation
Target: 
```
-target=azurerm_key_vault_key.idpay-mil-key -target=azurerm_key_vault_key.idpay-pinblock-key
```
---

feat: Idp 1914 idpay code keys

---

src/domains/idpay-app/.terraform.lock.hcl
src/domains/idpay-app/04_apim_api_token_exchange.tf
src/domains/idpay-app/04_apim_api_token_exchange_merchants.tf
src/domains/idpay-app/README.md

IDP-1884 moving Selfcare Oidc file exposure into CDN
Target: 
```
-target=azurerm_storage_container.idpay_oidc_config -target=null_resource.upload_oidc_configuration -target=azurerm_api_management_api_operation_policy.idpay_token_exchange_policy -target=azurerm_api_management_api_operation_policy.idpay_merchants_token_exchange_policy
```
---

fix: IDP-1884 moving Selfcare Oidc file exposure into CDN

---

src/domains/idpay-common/03_database.tf

Change _id in the collection payment_instrument_code with the field userId
Target: 
```
-target=azurerm_cosmosdb_mongo_collection.mongodb_collections_idpay
```
---

fix: IDP-1977-cambiare-id-nella-collezione-payment-instrument-code

---

src/core/README.md
src/core/observability.tf
src/core/storage.tf

feat: Added private endpoint to management storage account

---

src/domains/idpay-common/01_keyvault_0.tf
src/domains/rtd-common/01_keyvault_0.tf

- added access policy for keys into kv for idpay and rtd
solve pipelines errors
Target: 
```
```
---

fix: RTD-2157 added access policy for keys in kv

---

src/domains/idpay-app/04_apim_api_token_exchange_merchants.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay_token_exchange/jwt_merchants_token_test.xml.tpl

- new policy token test for merchants portal
For testing purpose, linked to task [IDP-2027](https://pagopa.atlassian.net/browse/IDP-2027)
Target: 
```
azurerm_api_management_api_operation.idpay_merchants_token_exchange_test
azurerm_api_management_api_operation_policy.idpay_merchants_token_exchange_policy_test
```
---
[IDP-2027]: https://pagopa.atlassian.net/browse/IDP-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IDP-2027] added policy token test for merchants portal

---

src/core/99_outputs.tf
src/core/README.md
src/core/dns_private.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/messages.tf
src/core/network.tf

feat: Remove old eventhubs and their namespace

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_merchants_portal/openapi.merchants.portal.yml
src/domains/idpay-app/api/idpay_mil/idpay_mil_payment/openapi.mil.payment.yml
src/domains/idpay-app/api/idpay_min_int/openapi.min.int.yml
src/domains/idpay-app/api/idpay_payment_io/openapi.payment_io.yml.tpl
src/domains/idpay-app/api/idpay_qrcode_payment/io/openapi.qrcode_payment_io.yml.tpl

Target: 
```
module.idpay_merchants_portal
module.idpay_mil_payment
module.idpay_min_int
module.idpay_payment_io
module.idpay_qr_code_payment_io
```
---

fix: IDP-2125-aggiornamento-swagger

---

src/domains/idpay-app/api/idpay_assistance/openapi.assistance.yml
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml

Fix swagger return type
Target: 
```
module.idpay_api_assistance
module.idpay_initiative_portal
```
---

fix: IDP-1342-5-sp-uniformare-formato-dei-valori-restituiti-dagli-endpoint-di-get-delle-statistiche

---

src/domains/idpay-common/03_database.tf

- add index on `onboardedInitiatives` to improved query performance based on `$size`
Target: 
```
```
---

fix: added index to onboardingInitiatives

---

src/domains/idpay-app/api/idpay_mil/idpay_mil_merchant/put-merchant-upload-policy.xml.tpl
src/domains/idpay-app/api_product/mil_api/policy_mil.xml

- added a variable "isMerchantIdRequired", setted to "false", in upload merchants file through MIL
- fixed product policy MIL adding condition about new variable when it is "true" (default value for MIL policy)
To fix the required header in MIL policy: task [IDP-1558](https://pagopa.atlassian.net/browse/IDP-1558) and [IDP-2028](https://pagopa.atlassian.net/browse/IDP-2028)
Target: 
```
module.idpay_api_mil_product
module.idpay_mil_merchant
```
---
[IDP-1558]: https://pagopa.atlassian.net/browse/IDP-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDP-2028]: https://pagopa.atlassian.net/browse/IDP-2028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

fix: [IDP-1558] new variable for MIL policy for retrieving merchantId

---

src/domains/idpay-app/api/idpay_mil/idpay_mil_payment/get-public-key-policy.xml.tpl

- added a variable "isMerchantIdRequired", setted to "false", in getPublicKey through MIL
To fix a not required header in MIL policy: task [IDP-1558](https://pagopa.atlassian.net/browse/IDP-1558)
Target: 
```
module.idpay_mil_payment
```
---
[IDP-1558]: https://pagopa.atlassian.net/browse/IDP-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-1558] fix header not mandatory in getPublicKey policy for MIL

---

src/domains/idpay-app/04_apim_api_assistance.tf
src/domains/idpay-app/04_apim_api_io.tf
src/domains/idpay-app/04_apim_api_issuer.tf
src/domains/idpay-app/04_apim_api_portal.tf
src/domains/idpay-app/06_apim_fragments.tf
src/domains/idpay-app/api/idpay_assistance/get-beneficiary-iban.xml.tpl
src/domains/idpay-app/api/idpay_assistance/get-beneficiary-instruments.xml.tpl
src/domains/idpay-app/api/idpay_assistance/get-beneficiary-onboarding-family-status.xml.tpl
src/domains/idpay-app/api/idpay_assistance/get-beneficiary-onboarding-status.xml.tpl
src/domains/idpay-app/api/idpay_assistance/get-beneficiary-timeline-detail.xml.tpl
src/domains/idpay-app/api/idpay_assistance/get-beneficiary-timeline.xml.tpl
src/domains/idpay-app/api/idpay_assistance/get-beneficiary-wallet.xml.tpl
src/domains/idpay-app/api/idpay_assistance/openapi.assistance.yml
src/domains/idpay-app/api/idpay_initiative/get-beneficiary-iban.xml.tpl
src/domains/idpay-app/api/idpay_initiative/get-beneficiary-instruments.xml.tpl
src/domains/idpay-app/api/idpay_initiative/get-beneficiary-onboarding-family-status.xml.tpl
src/domains/idpay-app/api/idpay_initiative/get-beneficiary-onboarding-status.xml.tpl
src/domains/idpay-app/api/idpay_initiative/get-beneficiary-timeline-detail.xml.tpl
src/domains/idpay-app/api/idpay_initiative/get-beneficiary-timeline.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-readmission-discount.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-readmission-refund.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-suspension-discount.xml.tpl
src/domains/idpay-app/api/idpay_initiative/put-initiative-suspension-refund.xml.tpl
src/domains/idpay-app/api_fragment/pdv-tokenizer.xml
src/domains/idpay-app/api_product/app_io/policy_io.xml.tpl
src/domains/idpay-app/api_product/app_issuer/policy_issuer.xml.tpl

This PR proposes to centralize in a fragment the policy of PDV tokenizer -> [IDP-2124](https://pagopa.atlassian.net/browse/IDP-2124)
- Modified fragment "apim-pdv-tokenizer" adding retry of send-request
- Added fragment in all idpay policy that use PDV tokenizer
- Added fragment in Issuer and IO policy product
Target: 
```
azapi_resource.apim-pdv-tokenizer
module.idpay_api_io_product
module.idpay_api_issuer_product
module.idpay_api_assistance
module.idpay_initiative_portal
```
---
[IDP-2124]: https://pagopa.atlassian.net/browse/IDP-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IDP-2124] centralize policy pdv for idpay apim

---

.github/workflows/static_analysis.yml
README.md
src/aks-platform/03_aks_0.tf
src/aks-platform/README.md
src/core/.terraform.lock.hcl
src/domains/idpay-common/.terraform.lock.hcl
src/domains/tae-app/.terraform.lock.hcl

- Dynamic folder calculation
- HCL files upgrade
- Add github badge static analysis
Fix for github action static analysis
Target: 
```
```
---

fix: RTD-2292 Static analysis

---

README.md
src/aks-platform/.terraform.lock.hcl
src/core/.terraform.lock.hcl
src/core/99_main.tf
src/core/README.md
src/core/observability.tf
src/domains/tae-app/.terraform.lock.hcl
src/domains/tae-app/03_pipeline.tf
src/domains/tae-app/99_main.tf
src/domains/tae-app/README.md
src/domains/tae-common/02_blob_storage.tf

- tae-app and core upgrated azurerm to version 3.40.0 to allow to remove deprecated diagnostic settings
- removed deprecated diagnostics setting to avoid problem with the remove of diagnostic settings classic
Diagnostic settings classic will be removed, so we need to clean all file to avoid references to this type of resources
Target: 
```
```
---

feat: RTD-2311 removed diagnostic settings classic

---

src/domains/tae-app/03_pipeline.tf
src/domains/tae-app/pipelines/data-explorer-activities/duplicateAndInvalidateFlow.json
src/domains/tae-app/pipelines/data-explorer-activities/purgeInvalidFlow.json
src/domains/tae-app/pipelines/foreach-activities/invalidateEachFlow.json

This PR proposes to make the invalidate flow pipeline accept an array of flow as parameter instead of a single file.
- cycle through flows as arguments and invalidate them
with this changes we can invalidate flows in batch.
Target: 
```
-target=azurerm_data_factory_pipeline.invalidate_flow
```
---

feat: [RTD-2317] Invalidate array of flows

---

src/domains/tae-app/00_monitor.tf

This PR proposes to add more info in `tae-p-failed-get-sender-ade-ack-list` query result.
- add `lastError_reason_s` to projection.
With these changes the Operations team will be facilitated to identify the problem.
Target: 
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.failure_on_sender_ade_ack_list
```
---

feat: [RTD-2289] Increase query info of tae-p-failed-get-sender-ade-ack-list

---

src/domains/tae-app/01_linked_service.tf
src/domains/tae-common/04_datafactory.tf
src/domains/tae-common/README.md

This PR moves kusto principal service from tea-common terraform state to tae-app
Target: 
```
```
---

chore: [RTD-2291] Remove redundant kusto principal assignment

---

src/domains/tae-app/03_pipeline.tf
src/domains/tae-app/pipelines/copy-activities/deleteInvalidatedFlowFromCosmos.json
src/domains/tae-app/pipelines/foreach-activities/invalidateEachFlow.json

This PR proposes to add an activity that set a TTL for records belonging to an invalid flow.
- add copy activity inside for-each loop.
With this change we clean up CosmosDB from invalid flows that shouldn't be acked.
Target: 
```
-target=azurerm_data_factory_pipeline.invalidate_flow
```
---

feat: [RTD-2323] Clean Cosmos records while invalidating flow

---

src/core/README.md
src/core/azure_devops_agent.tf

Now azdo use the new vmss
Target: 
```
```
---

feat: Removed azdoa-vmss-li because deprecated

---

src/core/README.md
src/core/identity_rg.tf
src/domains/idpay-app/.terraform.lock.hcl
src/domains/idpay-app/03_serviceaccounts_azure_devops.tf
src/domains/idpay-app/99_main.tf
src/domains/idpay-app/README.md
src/domains/rtd-app/.terraform.lock.hcl
src/domains/rtd-app/03_serviceaccounts_azure_devops.tf
src/domains/rtd-app/99_main.tf
src/domains/rtd-app/README.md
src/k8s/README.md
src/k8s/outputs.tf
src/k8s/serviceaccounts.tf

feat: Added identity rg

---

src/k8s/README.md
src/k8s/outputs.tf
src/k8s/secrets.tf
src/k8s/subscriptions/DEV-CSTAR/terraform.tfvars
src/k8s/subscriptions/PROD-CSTAR/terraform.tfvars
src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars
src/k8s/variables.tf

chore: remove secrets copying from rtd kv to old k8s

---

src/packer/00_network.tf
src/packer/02_dns_forwarder.tf
src/packer/README.md

Fix PR [#1221](https://github.com/pagopa/cstar-infrastructure/pull/1221) 
Target: 
```
```
---

fix: Dns forwarder packer

---

src/core/README.md
src/core/azure_devops_agent.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars
src/core/variables.tf

Improve machine capacity to speed up workloads
Target: 
```
```
---

feat: Updated agents sku for azdo

---

src/domains/idpay-app/13_config_kafka_connectors.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/kafka-connectors/transaction_in_progress_connector.json

[IDP-2351](https://pagopa.atlassian.net/browse/IDP-2351)
- renamed _cosmos_connector_  in _transaction_in_progress_connector_
- added tolerance and log error in config _transaction_in_progress_connector_
In order to log error events and to avoid blocking publication on the queue idpay-transaction
Target: 
```
terracurl_request.cosmos_connector
terracurl_request.transaction_in_progress_connector
```
In addition, it is necessary to delete the old cosmos-connector
---
[IDP-2351]: https://pagopa.atlassian.net/browse/IDP-2351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-2351] added tolerance and log error in transaction_in_progress_connector

---

src/domains/idpay-app/04_apim_api_mil.tf
src/domains/idpay-app/api/idpay_mil/idpay_mil_wallet/delete-instrument-policy.xml.tpl
src/domains/idpay-app/api/idpay_mil/idpay_mil_wallet/get-code-status-policy.xml.tpl
src/domains/idpay-app/api/idpay_mil/idpay_mil_wallet/openapi.mil.wallet.yml
src/domains/idpay-app/api/idpay_mil/idpay_mil_wallet/post-generate-idpaycode-policy.xml.tpl
src/domains/idpay-app/api/idpay_mil/idpay_mil_wallet/put-enroll-instrument-idpaycode-policy.xml.tpl
src/domains/idpay-app/api/idpay_mil/idpay_mil_wallet/put-enroll-instrument-policy.xml.tpl
src/domains/idpay-app/api/idpay_mil/idpay_mil_wallet/put-unsubscribe-policy.xml.tpl

This PR is related to task [IDP-2332](https://pagopa.atlassian.net/browse/IDP-2332)
- added new api for product mil_citizen: get status idpay_code, generate and enroll idpay_code
Target: 
```
module.idpay_mil_wallet
```
---
[IDP-2332]: https://pagopa.atlassian.net/browse/IDP-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [IDP-2332] new api of discount flow MIL

---

src/domains/idpay-common/03_database.tf
src/domains/idpay-common/env/dev/terraform.tfvars
src/domains/idpay-common/env/prod/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

- Added new consumer group for ms reward-calculator to idpay-transaction topic
- Added index pendinfTrx into user_initiative_counters collection
Target: 
```
module.event_hub_idpay_00
azurerm_key_vault_secret.event_hub_keys_idpay_00
azurerm_cosmosdb_mongo_collection.mongodb_collections_idpay
```
---

feat: [IDP-2296] Added new consumer-group for idpay-transaction topic

---

src/domains/idpay-app/kafka-connectors/transaction_in_progress_connector.json

- Replace filter CANCELED with CANCELLED on pipeline of transaction_in_progress connector configuration
Target: 
```
terracurl_request.transaction_in_progress_connector
```
---

fix: [IDP-2368] update transaction_in_progress_connector on pipeline filter

---

src/domains/idpay-app/02_namespace_domain.tf
src/domains/idpay-common/01_keyvault_0.tf

IDP-2370 fix KeyVault Encryption permission
Changing the encryption algorithm from RSA_OAEP to RSA_OAEP_256 requires the "encrypt" permission.
This will fix the behavior configured with the PR #1150 requested by the ticket IDP-1935
Target: 
```
idpay-common:
azurerm_key_vault_access_policy.adgroup_developers_policy
azurerm_key_vault_access_policy.adgroup_externals_policy
idpay-app:
module.domain_pod_identity
```
---

fix: IDP-2370 fix KeyVault Encryption permission

---

src/domains/tae-app/03_pipeline.tf
src/domains/tae-app/99_variables.tf
src/domains/tae-app/README.md
src/domains/tae-app/env/dev/terraform.tfvars
src/domains/tae-app/env/prod/terraform.tfvars
src/domains/tae-app/env/uat/terraform.tfvars
src/domains/tae-app/pipelines/report-duplicate-aggregates/activities.json

feat: [RTD-2417] Added TAE report pipeline

---

src/domains/tae-app/03_pipeline.tf
src/domains/tae-app/99_variables.tf
src/domains/tae-app/README.md
src/domains/tae-app/env/dev/terraform.tfvars
src/domains/tae-app/env/prod/terraform.tfvars
src/domains/tae-app/env/uat/terraform.tfvars
src/domains/tae-app/pipelines/report-merchants/activities.json

This PR proposes to add the ADF pipeline responsible to generate the report TAE for merchants.
- add pipeline
- fix `│ Warning: Quoted references are deprecated`
Target: 
```
-target=azurerm_data_factory_pipeline.report_merchants
```
---

feat: [RTD-2428] add report merchants pipeline adf

---

src/domains/idpay-common/04_service_bus.tf
src/domains/idpay-common/README.md

- Added resource for new service bus queue "idpay-payment-timeout"
- Added consumer access policy for queue "idpay-payment-timeout"
- Added consumer connection string into keyvault
Target: 
```
azurerm_servicebus_queue.idpay-payment-timeout
azurerm_servicebus_queue_authorization_rule.idpay-payment-timeout-consumer
azurerm_key_vault_secret.idpay-payment-timeout-consumer-sas-key
```
---

feat: IDP-2309 Create serviceBus queue for timeout

---

src/domains/idpay-common/04_cdn.tf

Task IDP-2335
- add header x-frame-options in idpay-cdn
Target: 
```
module.idpay_cdn
```
---

fix: [IDP-2335] add header x-frame-options in idpay-cdn

---

src/domains/idpay-app/api/idpay_group/openapi.group.yml

- [Added new exception code](https://pagopa.atlassian.net/browse/IDP-2363)
New codes have been added to remove sonar warnings
Target: 
```
```
---

fix: [IDP-2363] Added new exception code

---

src/domains/rtd-app/04_api_rtd.tf
src/domains/rtd-app/api/rtd_filereporter/openapi.yml

This PR proposes to expose the endpoint for report v2 on the report API.
Target: 
```
-target=module.rtd_filereporter
```
---

feat: add operation and openapi for report v2

---

src/core/env/prod/terraform.tfvars

aggiunto ip NEXI per accesso SFTP
Necessari accesso
Target: 
```
```
---

feat: [RTD-2497]  Aggiunta ip Nexi

---

src/core/.terraform.lock.hcl
src/core/env/prod/terraform.tfvars
src/core/storage.tf

- storage alligned
- kusto purge enabled
Target: 
```
```
---

fix: Align CORE terraform with Azure state

---

src/domains/tae-app/00_monitor.tf

With this change we avoid basing missing step alert on blob logs. Instead decrypter logs are used.
- use AppTraces instead of StorageBlobLogs.
Target: 
```
-target=azurerm_monitor_scheduled_query_rules_alert_v2.file-not-processed-by-decrypter
```
---

fix: [RTD-2575] Use decrypter logs instead of blob storage logs for alert missing steps

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_mil/idpay_mil_onboarding/openapi.mil.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl

- Update SelfConsentDTO  object
Target: 
```
-target=module.idpay_mil_onboarding
-target=module.idpay_onboarding_workflow_io
```
---

fix: [IDP-2477] update SelfConsentDTO for onboarding

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/README.md

chore: [RTD-2577] delete disabled cstar-p-file-register-file-already-present alert

---

src/domains/tae-app/00_monitor.tf

Solve these 2 tasks:
https://pagopa.atlassian.net/browse/RTD-2584
https://pagopa.atlassian.net/browse/RTD-2581
Target: 
```
```
---

chore: [RTD-2581] change severity level

---

src/domains/rtd-app/04_eventgrid.tf

fix: added event filter type for wallet subscription

---

src/domains/rtd-app/04_eventgrid.tf

chore: revert duplicate property

---

src/domains/tae-app/00_monitor.tf

This PR propose to include a failed metadata setting among alert causes.
Target: 
```
```
---

feat:  [TAE-206] Add cause to trigger failed metadata set in report

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/README.md

Add an alert to notify through slack a decrypted local blob file deletion failed.
Target: 
```
```
---

chore: [TAE-223] add alert for fail delete local blob

---

src/domains/mil-common-poc/00_network.tf
src/domains/mil-common-poc/01_network.tf
src/domains/mil-common-poc/03_eventhub.tf
src/domains/mil-common-poc/99_locals.tf
src/domains/mil-common-poc/99_variables.tf
src/domains/mil-common-poc/README.md
src/domains/mil-common-poc/env/weu-dev/terraform.tfvars
src/domains/mil-common-poc/env/weu-prod/terraform.tfvars
src/domains/mil-common-poc/env/weu-uat/terraform.tfvars

- eventhub setup completed in DEV
- cosmosdb fix network configuration in DEV
Allow to use Eventhub in DEV
Target: 
```
```
---

feat(mil): Eventhub setup & cosmosdb network fix

---

src/domains/mil-secrets-poc/01_keyvault.tf

Missed one property for externals
Target: 
```
```
---

fix(mil): External fix key policy

---

src/domains/tae-app/pipelines/lookup-activities/extractPendingFilesInCosmos.json

This PR proposes to add a cast to int of the pipeline parameter.
Target: 
```
-target=azurerm_data_factory_pipeline.pending_files_in_Cosmos
```
[Link to test results](https://adf.azure.com/en/monitoring/pipelineruns/b8446bc2-7ca8-4ac5-b803-040bc6e5d22b?factory=%2Fsubscriptions%2F88c709b0-11cf-4450-856e-f9bf54051c1d%2FresourceGroups%2Fcstar-p-weu-tae-df-rg%2Fproviders%2FMicrosoft.DataFactory%2Ffactories%2Fcstar-p-weu-tae-df)
---

fix: [TAE-276] Fix cast pending pipeline parameter

---

src/domains/mil-app-poc/.terraform.lock.hcl
src/domains/mil-app-poc/04_apim_emd.tf
src/domains/mil-app-poc/api/emd_message_core/openapi.emd.yml
src/domains/mil-app-poc/api_product/emd/policy_emd.xml
src/domains/mil-app-poc/env/weu-dev/terraform.tfvars
src/domains/mil-app-poc/env/weu-prod/terraform.tfvars
src/domains/mil-app-poc/env/weu-uat/terraform.tfvars
src/domains/mil-common-poc/03_eventhub.tf

- Update eventhub configuration
- Update policy configuration
Target: 
```
-target=module.emd_message_core
-target=module.emd_api_product
-target=azurerm_api_management_policy_fragment.apim-validate-token-mil
```
---

fix: update event hub configuration and swagger

---

src/core/.terraform.lock.hcl
src/domains/mil-app-poc/.terraform.lock.hcl
src/domains/mil-app-poc/01_network.tf
src/domains/mil-app-poc/08_k8s_configmaps.tf
src/domains/mil-app-poc/99_main.tf
src/domains/mil-app-poc/README.md
src/domains/mil-app-poc/env/weu-dev/terraform.tfvars
src/domains/mil-app-poc/env/weu-uat/terraform.tfvars
src/domains/mil-common-poc/.terraform.lock.hcl
src/domains/mil-common-poc/env/weu-dev/terraform.tfvars
src/domains/mil-common-poc/env/weu-uat/terraform.tfvars
src/domains/mil-secrets-poc/.terraform.lock.hcl
src/domains/mil-secrets-poc/99_main.tf
src/domains/mil-secrets-poc/README.md
src/domains/mil-secrets-poc/secret/weu-dev/noedit_secret_core_enc.json
src/domains/mil-secrets-poc/secret/weu-uat/noedit_secret_core_enc.json

- Applied UAT MIL (app, common, secrets)
- Upload Hype info (DEV & UAT) in secrets
Target: 
```
```
---

feat: Apply MIL uat

---

src/aks-platform/03_aks_0.tf
src/domains/idpay-app/00_key_vault.tf
src/domains/idpay-common/01_keyvault_0.tf
src/domains/idpay-common/04_cdn.tf
src/domains/rtd-common/01_keyvault_0.tf
src/domains/rtd-common/03_database.tf

Install workload identity for domains in UAT
Target: 
```
```
---

feat: workload-identity@uat

---

src/domains/idpay-common/03_database.tf
src/domains/idpay-common/env/dev/terraform.tfvars
src/domains/idpay-common/env/prod/terraform.tfvars
src/domains/idpay-common/env/uat/terraform.tfvars

- Update mongo version to 7.0.
- This update does not allow you to re-enable the MongoDB health check
Target: 
```
```
---

fix: Upgrade mongo version to 7.0

---

src/domains/rtp-secrets/secret/weu-prod/secret.ini

This PR propose to fix a typo in configuration env
Target: 
```
```
---

fix: typo in secrets env

---

src/domains/tier-0-common/env/dev/terraform.tfvars
src/domains/tier-0-common/env/prod/terraform.tfvars
src/domains/tier-0-common/env/uat/terraform.tfvars

breaking: [SRTP-90] Only not-admin mil-auth operations are now published on the APIM.

---

src/domains/mil-secrets-poc/secret/weu-dev/noedit_secret_core_enc.json

feat: MMC-93 add fucino secrets

---

src/domains/rtp-common/README.md
src/domains/rtp-common/cosmosdb_accounts.tf

chore: srtp create activator db

---

src/domains/rtp-app/04_role_assignments.tf
src/domains/rtp-app/README.md

fix: add kv user role assigment for activator

---

src/domains/rtp-common/README.md
src/domains/rtp-common/appinsights.tf

feat: [SRTP-115] Add appinsights connection to string to rtp kv

---

scripts/terraform.sh
src/domains/mcshared-common/99_main.tf
src/domains/mcshared-common/terraform.sh
src/domains/mcshared-common/variables.tf

Added the retrieving of subscription ID and the export of its value to ARM_SUBSCRIPTION_ID to enable the usage of azurerm provider 4.*.
Target: 
```
```
---

chore: Export of ARM_SUBSCRIPTION_ID.

---

src/domains/mcshared-common/role_assignments.tf
src/domains/rtp-app/04_role_assignments.tf
src/domains/rtp-secrets/01_keyvault.tf

feat: "Key Vault Administrator" role on domain KV given to Developers group in prod environment.

---

src/domains/mcshared-common/cosmosdb_mongo_collections.tf
src/domains/mcshared-common/github_repository_environments.tf

feat: [SRTP-168] Added new collection to Mongo for mil-auth users.

---

src/domains/mil-app-poc/04_apim_emd.tf
src/domains/mil-app-poc/README.md
src/domains/mil-app-poc/api/emd_citizen/openapi.citizen.yml
src/domains/mil-app-poc/api/emd_citizen/post-insert-citizen-consent-policy.xml.tpl
src/domains/mil-app-poc/api/emd_citizen/put-update-citizen-consent-policy.xml.tpl
src/domains/mil-app-poc/api/emd_message_core/openapi.emd.yml
src/domains/mil-app-poc/api/emd_mil_citizen/get-citizen-consent-enabled-policy.xml.tpl
src/domains/mil-app-poc/api/emd_mil_citizen/get-citizen-consent-status-policy.xml.tpl
src/domains/mil-app-poc/api/emd_mil_citizen/openapi.mil.citizen.yml
src/domains/mil-app-poc/api/emd_mil_citizen/post-insert-citizen-consent-policy.xml.tpl
src/domains/mil-app-poc/api/emd_mil_citizen/put-update-citizen-consent-policy.xml.tpl

- Update emd swagger
- Update mil citizen swagger
- Update citizen swagger
Target: 
```
-target=module.emd_message_core
-target=module.emd_mil_citizen
-target=module.emd_citizen
```
---

fix: update emd swagger

---

src/domains/mil-app-poc/api/emd_citizen/openapi.citizen.yml
src/domains/mil-app-poc/api/emd_message_core/openapi.emd.yml
src/domains/mil-app-poc/api/emd_message_sender/openapi.emd_sender.yml
src/domains/mil-app-poc/api/emd_mil_citizen/openapi.mil.citizen.yml
src/domains/mil-app-poc/api/emd_tpp/openapi.tpp.yml

- Update emd swaggers
Target: 
```
-target=module.emd_tpp 
-target=module.emd_citizen
-target=module.emd_mil_citizen
-target=module.emd_message_core
```
---

fix: update swagger

---

src/domains/mcshared-common/cosmosdb_accounts.tf

breaking: MongoDB server version upgraded to v7.

---

src/domains/mil-app-poc/10_workload_identity.tf

fix: MIL workload identity

---

src/domains/rtp-common/03_database.tf
src/domains/rtp-common/README.md

This PR proposes to add a new cosmos collection for the RTPs
Target: 
```
```
---

feat: [SRTP-137] add collection rtps

---

src/core/observability.tf

feat: add ignore changes sku log analytics

---

src/domains/tae-app/00_monitor.tf
src/domains/tae-app/README.md

This PR introduces a new scheduled query rule alert in Azure to monitor decrypter failures during blob splitting. The alert ensures timely detection of critical issues affecting data processing.
- Added a new `azurerm_monitor_scheduled_query_rules_alert_v2` resource:
- **Alert Name**: `cstar-${var.env_short}-decrypter-failed-splitting-blob`
- **Description**: "Triggers an alert when a blob is not correctly split during processing."
- **Condition**: Triggers on SeverityLevel 3 logs with the message "Failed splitting blob."
- **Frequency**: Evaluates every 5 minutes (`PT5M`).
- Configured action groups:
- `send_to_operations`
- `send_to_zendesk`
- Set up tags for monitoring and resource identification.
- Scoped to production environments using `count = var.env_short == "p" ? 1 : 0`.
Target: …

feat: [TAE-219] add Azure alert for failed decrypter blob splitting

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_initiative/openapi.initiative.yml
src/domains/idpay-app/api/idpay_issuer_onboarding_workflow/openapi.issuer.onboarding.yml.tpl
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl
src/domains/idpay-app/api/idpay_wallet/get-wallet-detail-policy.xml.tpl
src/domains/idpay-app/api/idpay_wallet/get-wallet-policy.xml.tpl
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl
src/domains/idpay-common/03_database.tf

- Added free text and new initiativeRewardType
- Added new free text
- Update APIM policy for Accept new initiativeRewardType on organizationName: "Comune di Guidonia Montecelio".
- Add anpr_info collection
- Add self_declaration_text collection
Target: 
```
#IDPAY-APP
-target=module.idpay_wallet_io
-target=module.idpay_onboarding_workflow_issuer
-target=module.idpay_onboarding_workflow_io
-target=module.idpay_initiative_portal
#IDPAY-COMMON
-target=azurerm_cosmosdb_mongo_collection.mongodb_collections_idpay
```
---

feat: [IDP-2607] update APIM wallet and added free text field

---

src/domains/mil-secrets-poc/secret/weu-dev/noedit_secret_core_enc.json

feat: MIL add webview secrets

---

src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml
src/domains/idpay-app/api/idpay_onboarding_workflow/openapi.onboarding.yml.tpl

- Replace anyOf with oneOf on AppIO and onboarding swagger
Target: 
```
-target=module.idpay_onboarding_workflow_io
```
---

fix: IO Swagger

---

scripts/terraform.sh
src/domains/mcshared-common/terraform.sh

chore: Update terraform.sh

---

src/domains/idpay-app/04_apim_api_webview.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay-self-expense/get-redirect.xml.tpl
src/domains/idpay-app/api/idpay-self-expense/get-session.xml.tpl
src/domains/idpay-app/api/idpay-self-expense/login.xml.tpl
src/domains/idpay-app/api/idpay-self-expense/openapi.self-expense.yml.tpl
src/domains/idpay-app/api_product/webview/policy_webview.xml

- Added webview swagger
- Added webview product 
- Added webview API redirect policy
Target: 
```
#idpay-app#
-target=module.idpay_api_webview_product
-target=module.idpay_api_webview
```
---

feat: add webview swagger and new product and policy

---

src/domains/idpay-app/04_apim_api_webview.tf
src/domains/idpay-app/api/idpay-self-expense/get-redirect.xml.tpl
src/domains/idpay-app/api/idpay-self-expense/get-session.xml.tpl
src/domains/idpay-app/api/idpay-self-expense/login.xml.tpl

- Update self expense ingress
- Update policy url
Target: 
```
#idpay-app#
-target=module.idpay_api_webview_product
-target=module.idpay_api_webview
```
---

fix: update ingress and policy for self-expense

---

src/domains/rtp-common/README.md
src/domains/rtp-common/storage.tf

Add a new storage account for RTP.
Target: 
```
```
---

chore: [SRTp-263] Add rtp storage account

---

src/domains/rtp-common/README.md
src/domains/rtp-common/storage.tf

chore: [SRTP-268] Add container in storage account rtp

---

src/domains/idpay-app/04_apim_api_io.tf
src/domains/idpay-app/99_variables.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay_appio_full/openapi.appio.full.yml
src/domains/idpay-app/api/idpay_wallet/get-wallet-detail-policy.xml.tpl
src/domains/idpay-app/api/idpay_wallet/get-wallet-policy.xml.tpl
src/domains/idpay-app/api/idpay_wallet/openapi.wallet.yml.tpl
src/domains/idpay-app/env/dev/terraform.tfvars
src/domains/idpay-app/env/prod/terraform.tfvars
src/domains/idpay-app/env/uat/terraform.tfvars

- Added serviceId on wallet response
- Edit webViewUrl
Target: 
```
-target=module.idpay_wallet_io
```
---

feat: added serviceId on wallet response

---

src/domains/idpay-app/env/dev/terraform.tfvars
src/domains/idpay-app/env/prod/terraform.tfvars
src/domains/idpay-app/env/uat/terraform.tfvars

- Update webViewUrl
Target: 
```
-target=module.idpay_wallet_io
```
---

fix: added loginUrl and precommit

---

src/domains/idpay-app/api/idpay-self-expense/get-child-for-userid.xml.tpl

- Update policy webview on getChild
Target: 
```
-target=module.idpay_api_webview
```
---

fix: update policy webview on getChild

---

src/core/00_data.tf
src/core/99_locals.tf
src/core/README.md
src/core/dns_private.tf

Allow to use private link dns for container app
Target: 
```
```
---

feat: Container app added privatelink dns

---

src/core/00_data.tf
src/core/99_locals.tf
src/core/README.md
src/core/dns_private.tf
src/core/network.tf

Allow to use the VPN and the privatelink dns, configured inside the core vnet
Target: 
```
```
---

feat: Vnet core peering and dns private link with vnets in secure hub

---

src/domains/idpay-common/04_service_bus.tf

chore(idpay): upgrade tls version service bus

---

src/core/99_locals.tf
src/core/dns_private.tf
src/core/network.tf

the peerings and the dns private link for table and queue was fixed to allow the connection with vpn into secure hub private resource
Target: 
```
```
---

fix: VNET peering and dns link to allow VPN to connect to secure hub

---

src/domains/idpay-app/09_webview_storage.tf
src/domains/idpay-app/README.md
src/domains/idpay-app/api/idpay-self-expense/openapi.self-expense.yml.tpl

- Create webview storage for pdf
- Update files upload
Target: 
```
-target=module.idpay_webview_storage
-target=azurerm_private_endpoint.idpay_webview_storage_private_endpoint 
-target=azurerm_storage_container.idpay_webview_container
-target=azurerm_key_vault_secret.webview_storage_access_key 
-target=azurerm_key_vault_secret.webview_storage_connection_string 
-target=azurerm_role_assignment.webview_storage_data_contributor 
-target=module.idpay_api_webview
```
---

feat: create blob storage webview

---

src/core/00_data.tf
src/core/99_locals.tf
src/core/README.md
src/core/dns_private.tf

feat: Added container app private DNS

---

src/core/00_data.tf
src/core/99_locals.tf
src/core/README.md
src/core/dns_private.tf

feat: Sync and clean code for private dns container app

---

src/core/99_variables.tf
src/core/README.md
src/core/app_gateway.tf
src/core/env/dev/terraform.tfvars
src/core/env/prod/terraform.tfvars
src/core/env/uat/terraform.tfvars

This PR proposes to add new intermediate CA for internal certificate signing.
- add new intermediate bundle (root+intermediate) as secret beside old intermediate CA
The old intermediate CA is expiring next year, so we need to sign certificate lasting more than its duration. This led us to the creation of new intermediates.
Target: 
```
--target=module.app_gw_maz
```
---

feat: add new intermediate CA

---

.devops/core-secrets-code-review-pipelines.yml
.devops/core-secrrets-deploy-pipelines.yml

Introduce new YAML definitions for deployment and code review pipelines targeting DEV, UAT, and PROD environments. The templates include parameterized configurations and utilize shared repository definitions for consistency. These pipelines streamline environment-specific tasks and enable more efficient CI/CD processes.
Introduce YAML pipelines for deploying core-secrets and conducting code reviews in DEV, UAT, and PROD environments. These pipelines enhance CI/CD processes by centralizing configurations and streamlining tasks across all environments
Target: 
```
```
---

feat: [PAYMCLOUD-302] Add pipelines for core-secrets deployment and code review

---

src/domains/mil-common-poc/03_redis.tf
src/domains/mil-common-poc/99_locals.tf
src/domains/mil-common-poc/README.md

Allow to save the redis info that allow the login
Target: 
```
```
---

feat: MMC-153 new secrets for redis cache login

---

src/domains/mil-common-poc/03_redis.tf
src/domains/mil-common-poc/99_variables.tf
src/domains/mil-common-poc/README.md
src/domains/mil-common-poc/env/dev/terraform.tfvars
src/domains/mil-common-poc/env/prod/terraform.tfvars
src/domains/mil-common-poc/env/uat/terraform.tfvars

A dedicated redis cache for MC project separated from IdPay
Target: 
```
```
---

feat: MMC-144 MC/MIL redis cache dedicated

---

src/domains/mil-app-poc/api/emd_citizen/openapi.citizen.yml
src/domains/mil-app-poc/api/emd_message_core/openapi.emd.yml
src/domains/mil-app-poc/api/emd_message_sender/openapi.emd_sender.yml
src/domains/mil-app-poc/api/emd_mil_citizen/openapi.mil.citizen.yml
src/domains/mil-app-poc/api/emd_mil_testing/openapi.mil.tpp.yml
src/domains/mil-app-poc/api/emd_payment_core/openapi.payment.yaml
src/domains/mil-app-poc/api/emd_tpp/openapi.tpp.yml

- Delete securitySchemes on every enviroment
- Update x-internal: false for production endpoint
Target: 
```
-target=module.emd_tpp
-target=module.emd_citizen 
-target=module.emd_message_core 
-target=module.emd_payment_core 
-target=module.emd_mil_citizen 
-target=module.emd_mil_tpp_testing
```
---

fix: handle securitySchemes on emd swagger

---

.devops/mil-code-review-pipelines.yml
.devops/mil-deploy-pipelines.yml
src/domains/mil-app-poc/api/emd_tpp/openapi.tpp.yml

- Update PSP reference 
Target: 
```
module.emd_tpp
```
---

fix: update PSP reference on tpp swagger

---

src/domains/mil-app-poc/.terraform.lock.hcl
src/domains/mil-app-poc/04_apim_emd.tf
src/domains/mil-app-poc/99_variables.tf
src/domains/mil-app-poc/README.md
src/domains/mil-app-poc/env/dev/terraform.tfvars
src/domains/mil-app-poc/env/prod/terraform.tfvars
src/domains/mil-app-poc/env/uat/terraform.tfvars

- Update rate limit for emd product
Target: 
```
-target=module.emd_api_product
```
---

fix: update rate limit

---

src/domains/mil-app-poc/api_fragment/validate-token-mil.xml

- Add clock skew to milAuth validation token 
Target: 
```
-target=azurerm_api_management_policy_fragment.apim-validate-token-mil
-target=module.emd_tpp
-target=module.emd_citizen 
-target=module.emd_message_core 
-target=module.emd_payment_core 
-target=module.emd_mil_citizen 
-target=module.emd_mil_tpp_testing
```
---

fix: add clock skew to mil authentication

---

src/domains/mil-app-poc/api/emd_citizen/openapi.citizen.yml
src/domains/mil-app-poc/api/emd_mil_citizen/openapi.mil.citizen.yml

- Update Error code
Target: 
```
-target=module.emd_citizen 
-target=module.emd_mil_citizen
```
---

fix: update-swagger-citizen

---

src/core/README.md
src/core/dns_private.tf
src/domains/mcshared-common/README.md
src/domains/mcshared-common/private_dns_zones.tf
src/domains/mcshared-common/private_endpoints.tf

fix: Private DNS zone for Key Vault moved from mcshared domain to core.

---

src/domains/rtp-common/03_database.tf
src/domains/rtp-common/README.md
src/domains/rtp-common/storage_share.tf

chore: [SRTP-401] Add storage account and file share

---

src/domains/mil-app-poc/04_apim_emd.tf
src/domains/mil-app-poc/README.md
src/domains/mil-app-poc/api/emd_tpp/get-network-connection.xml.tpl
src/domains/mil-app-poc/api/emd_tpp/get-token-section.xml.tpl
src/domains/mil-app-poc/api/emd_tpp/get-tpp-detail.xml.tpl
src/domains/mil-app-poc/api/emd_tpp/post-save-tpp-policy.xml.tpl
src/domains/mil-app-poc/api/emd_tpp/put-update-token-section-policy.xml.tpl
src/domains/mil-app-poc/api/emd_tpp/put-update-tpp-consent-policy.xml.tpl
src/domains/mil-app-poc/api/emd_tpp/put-update-tpp-detail-policy.xml.tpl
src/domains/mil-app-poc/api_product/emd/tpp/policy_emd.xml

- Add TPP product
- Update policy for openapi.tpp.yml
Target: 
```
-target=module.emd_tpp_product
-target=module.emd_tpp
```
---

fix: add tpp product

---

src/core/app_gateway.tf

feat: [SRTP-416] Fix rtp-cb rewrite rule

---

src/domains/rtp-common/README.md
src/domains/rtp-common/storage.tf

chore: [SRTP-431] Add container for payees registry.

---

src/core/README.md
src/core/app_gateway.tf

use more specific rewrite urls 
Target: 
```
```
---

fix: SRTP-476 better rewrite urls for App Gw

---

src/core/99_main.tf
src/core/README.md
src/core/app_gateway.tf

fix: IDP-2663 app gw added rewrite url for api-io

---

src/core/network.tf
src/core/network_aks_domains.tf

Now the VPN gateway is in Italy North, so we need to remove all the reference for the VPN and fix the network peering rules
Target: 
```
```
---

fix: network peerings & removing the old vpn gateway resources

---

src/core/network_aks_domains.tf
src/core/network_pair.tf

fix: Network peerings and removing the old vpn gateway

---

src/core/app_gateway.tf

fix: Appgw rewrite idpay ITN

---

src/aks-platform/00_network.tf
src/aks-platform/03_aks_dns_private_link.tf
src/aks-platform/99_locals.tf
src/aks-platform/README.md

the aks dns wasn't linked to the need vpn vnet called hub
Target: 
```
```
---

fix: RTD-2616 aks weu has problem to be reached by vpn user with kubectl

---

src/domains/rtp-common/03_database.tf
src/domains/rtp-common/README.md

…abase
This pull request removes the activation collection from the rtp MongoDB database.
The removal has been requested as the collection is no longer needed and should be cleaned up to reduce unused resources.
- Removed the azurerm_cosmosdb_mongo_collection.activations resource from the Terraform configuration (03_database.tf).
This change is needed to clean up infrastructure by removing an unused MongoDB collection named activation inside the rtp database.
Target: 
```
```
---

fix: [SRTP-537] deleted the collection activations inside the rtp database

---

src/domains/rtp-common/03_database.tf

This pull request introduces a **composite index** on the `rtps` Cosmos DB Mongo collection.  
The index includes the fields:
- `operationId` (type: Long)
- `eventDispatcher` (type: String)
- Added new composite index on the `rtps` collection: `["operationId", "eventDispatcher"]`.
This composite index on operationId and eventDispatcher is introduced to optimize query performance on the rtps collection.
Target: 
```
```
---

feat: [SRTP-558] add composite index on operationId and eventDispatcher

---

src/domains/rtp-common/99_locals.tf
src/domains/rtp-common/99_variables.tf
src/domains/rtp-common/README.md
src/domains/rtp-common/data.tf
src/domains/rtp-common/env/dev/terraform.tfvars
src/domains/rtp-common/env/prod/terraform.tfvars
src/domains/rtp-common/env/uat/terraform.tfvars
src/domains/rtp-common/storage_share.tf

feat: SRTP-597-add-resource-rtp_sender_file_share_storage

---

src/core/app_gateway.tf

- Updated App Gateway access rules to include `rtd/mock-io` URI path pattern.
This change was required to grant access to resources related to the `rtd/mock-io` endpoint. It ensures the correct functionality and accessibility of these resources.
Target: 
```
```
---

feat: IDP-2774 Update App Gateway access rules for rtd/mock-io URI path

---

src/domains/mil-app-poc/21_workbook.tf
src/domains/mil-app-poc/README.md
src/domains/mil-app-poc/workbooks/EMDDashboardPRODv2.json.tpl
src/domains/mil-app-poc/workbooks/EMDDashboardUATv2.json.tpl

feat: Add MIL/Messaggi di cortesia/EMD workbook
